# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Zone Documents\ToF\Documents\GitHub\GOSLauncher_A3_Python_version\principale.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fenetre_Principale(object):
    def setupUi(self, Fenetre_Principale):
        Fenetre_Principale.setObjectName("Fenetre_Principale")
        Fenetre_Principale.resize(529, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gfx/GOSLauncherA3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Fenetre_Principale.setWindowIcon(icon)
        Fenetre_Principale.setStyleSheet("background-color: rgb(236, 236, 236);")
        Fenetre_Principale.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralWidget = QtWidgets.QWidget(Fenetre_Principale)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 511, 491))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_ModsGOS = QtWidgets.QWidget()
        self.Tab_ModsGOS.setObjectName("Tab_ModsGOS")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Tab_ModsGOS)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 491, 451))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(381, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_Template = QtWidgets.QWidget()
        self.tab_Template.setObjectName("tab_Template")
        self.listWidget_Template = QtWidgets.QListWidget(self.tab_Template)
        self.listWidget_Template.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Template.setFont(font)
        self.listWidget_Template.setStyleSheet("")
        self.listWidget_Template.setObjectName("listWidget_Template")
        self.pushButton_Mods_Template_RefreshList = QtWidgets.QPushButton(self.tab_Template)
        self.pushButton_Mods_Template_RefreshList.setGeometry(QtCore.QRect(370, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Template_RefreshList.setFont(font)
        self.pushButton_Mods_Template_RefreshList.setObjectName("pushButton_Mods_Template_RefreshList")
        self.pushButton_Mods_Template_InvSelect = QtWidgets.QPushButton(self.tab_Template)
        self.pushButton_Mods_Template_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Template_InvSelect.setFont(font)
        self.pushButton_Mods_Template_InvSelect.setObjectName("pushButton_Mods_Template_InvSelect")
        self.pushButton_Mods_Template_SelectAll = QtWidgets.QPushButton(self.tab_Template)
        self.pushButton_Mods_Template_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Template_SelectAll.setFont(font)
        self.pushButton_Mods_Template_SelectAll.setObjectName("pushButton_Mods_Template_SelectAll")
        self.label_GFX_Template = QtWidgets.QLabel(self.tab_Template)
        self.label_GFX_Template.setGeometry(QtCore.QRect(370, 190, 101, 101))
        self.label_GFX_Template.setText("")
        self.label_GFX_Template.setPixmap(QtGui.QPixmap("gfx/logo-gos.png"))
        self.label_GFX_Template.setScaledContents(True)
        self.label_GFX_Template.setObjectName("label_GFX_Template")
        self.comboBox_ChoixApparence = QtWidgets.QComboBox(self.tab_Template)
        self.comboBox_ChoixApparence.setGeometry(QtCore.QRect(360, 140, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ChoixApparence.setFont(font)
        self.comboBox_ChoixApparence.setObjectName("comboBox_ChoixApparence")
        self.tabWidget_2.addTab(self.tab_Template, "")
        self.tab_Framework = QtWidgets.QWidget()
        self.tab_Framework.setObjectName("tab_Framework")
        self.listWidget_Framework = QtWidgets.QListWidget(self.tab_Framework)
        self.listWidget_Framework.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Framework.setFont(font)
        self.listWidget_Framework.setObjectName("listWidget_Framework")
        self.pushButton_Mods_Framework_SelectAll = QtWidgets.QPushButton(self.tab_Framework)
        self.pushButton_Mods_Framework_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Framework_SelectAll.setFont(font)
        self.pushButton_Mods_Framework_SelectAll.setObjectName("pushButton_Mods_Framework_SelectAll")
        self.pushButton_Mods_Framework_RefreshList = QtWidgets.QPushButton(self.tab_Framework)
        self.pushButton_Mods_Framework_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Framework_RefreshList.setFont(font)
        self.pushButton_Mods_Framework_RefreshList.setObjectName("pushButton_Mods_Framework_RefreshList")
        self.label_GFX_Framework = QtWidgets.QLabel(self.tab_Framework)
        self.label_GFX_Framework.setGeometry(QtCore.QRect(370, 140, 101, 91))
        self.label_GFX_Framework.setText("")
        self.label_GFX_Framework.setPixmap(QtGui.QPixmap("gfx/atelier.png"))
        self.label_GFX_Framework.setScaledContents(True)
        self.label_GFX_Framework.setObjectName("label_GFX_Framework")
        self.pushButton_Mods_Framework_InvSelect = QtWidgets.QPushButton(self.tab_Framework)
        self.pushButton_Mods_Framework_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Framework_InvSelect.setFont(font)
        self.pushButton_Mods_Framework_InvSelect.setObjectName("pushButton_Mods_Framework_InvSelect")
        self.tabWidget_2.addTab(self.tab_Framework, "")
        self.tab_Islands = QtWidgets.QWidget()
        self.tab_Islands.setObjectName("tab_Islands")
        self.listWidget_Islands = QtWidgets.QListWidget(self.tab_Islands)
        self.listWidget_Islands.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Islands.setFont(font)
        self.listWidget_Islands.setObjectName("listWidget_Islands")
        self.pushButton_Mods_Islands_SelectAll = QtWidgets.QPushButton(self.tab_Islands)
        self.pushButton_Mods_Islands_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Islands_SelectAll.setFont(font)
        self.pushButton_Mods_Islands_SelectAll.setObjectName("pushButton_Mods_Islands_SelectAll")
        self.pushButton_Mods_Islands_InvSelect = QtWidgets.QPushButton(self.tab_Islands)
        self.pushButton_Mods_Islands_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Islands_InvSelect.setFont(font)
        self.pushButton_Mods_Islands_InvSelect.setObjectName("pushButton_Mods_Islands_InvSelect")
        self.label_GFX_Islands = QtWidgets.QLabel(self.tab_Islands)
        self.label_GFX_Islands.setGeometry(QtCore.QRect(370, 130, 101, 101))
        self.label_GFX_Islands.setText("")
        self.label_GFX_Islands.setPixmap(QtGui.QPixmap("gfx/IslandStone.png"))
        self.label_GFX_Islands.setScaledContents(True)
        self.label_GFX_Islands.setObjectName("label_GFX_Islands")
        self.pushButton_Mods_Islands_RefreshList = QtWidgets.QPushButton(self.tab_Islands)
        self.pushButton_Mods_Islands_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Islands_RefreshList.setFont(font)
        self.pushButton_Mods_Islands_RefreshList.setObjectName("pushButton_Mods_Islands_RefreshList")
        self.tabWidget_2.addTab(self.tab_Islands, "")
        self.tab_Units = QtWidgets.QWidget()
        self.tab_Units.setObjectName("tab_Units")
        self.listWidget_Units = QtWidgets.QListWidget(self.tab_Units)
        self.listWidget_Units.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Units.setFont(font)
        self.listWidget_Units.setObjectName("listWidget_Units")
        self.label_GFX_Units = QtWidgets.QLabel(self.tab_Units)
        self.label_GFX_Units.setGeometry(QtCore.QRect(360, 150, 101, 81))
        self.label_GFX_Units.setText("")
        self.label_GFX_Units.setPixmap(QtGui.QPixmap("gfx/units.png"))
        self.label_GFX_Units.setScaledContents(True)
        self.label_GFX_Units.setObjectName("label_GFX_Units")
        self.pushButton_Mods_Units_InvSelect = QtWidgets.QPushButton(self.tab_Units)
        self.pushButton_Mods_Units_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Units_InvSelect.setFont(font)
        self.pushButton_Mods_Units_InvSelect.setObjectName("pushButton_Mods_Units_InvSelect")
        self.pushButton_Mods_Units_RefreshList = QtWidgets.QPushButton(self.tab_Units)
        self.pushButton_Mods_Units_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Units_RefreshList.setFont(font)
        self.pushButton_Mods_Units_RefreshList.setObjectName("pushButton_Mods_Units_RefreshList")
        self.pushButton_Mods_Units_SelectAll = QtWidgets.QPushButton(self.tab_Units)
        self.pushButton_Mods_Units_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Units_SelectAll.setFont(font)
        self.pushButton_Mods_Units_SelectAll.setObjectName("pushButton_Mods_Units_SelectAll")
        self.tabWidget_2.addTab(self.tab_Units, "")
        self.tab_Materiel = QtWidgets.QWidget()
        self.tab_Materiel.setObjectName("tab_Materiel")
        self.listWidget_Materiel = QtWidgets.QListWidget(self.tab_Materiel)
        self.listWidget_Materiel.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Materiel.setFont(font)
        self.listWidget_Materiel.setObjectName("listWidget_Materiel")
        self.pushButton_Mods_Materiel_SelectAll = QtWidgets.QPushButton(self.tab_Materiel)
        self.pushButton_Mods_Materiel_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Materiel_SelectAll.setFont(font)
        self.pushButton_Mods_Materiel_SelectAll.setObjectName("pushButton_Mods_Materiel_SelectAll")
        self.label_GFX_Materiel = QtWidgets.QLabel(self.tab_Materiel)
        self.label_GFX_Materiel.setGeometry(QtCore.QRect(370, 130, 101, 101))
        self.label_GFX_Materiel.setText("")
        self.label_GFX_Materiel.setPixmap(QtGui.QPixmap("gfx/hangar.png"))
        self.label_GFX_Materiel.setScaledContents(True)
        self.label_GFX_Materiel.setObjectName("label_GFX_Materiel")
        self.pushButton_Mods_Materiel_RefreshList = QtWidgets.QPushButton(self.tab_Materiel)
        self.pushButton_Mods_Materiel_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Materiel_RefreshList.setFont(font)
        self.pushButton_Mods_Materiel_RefreshList.setObjectName("pushButton_Mods_Materiel_RefreshList")
        self.pushButton_Mods_Materiel_InvSelect = QtWidgets.QPushButton(self.tab_Materiel)
        self.pushButton_Mods_Materiel_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Materiel_InvSelect.setFont(font)
        self.pushButton_Mods_Materiel_InvSelect.setObjectName("pushButton_Mods_Materiel_InvSelect")
        self.tabWidget_2.addTab(self.tab_Materiel, "")
        self.tab_Client = QtWidgets.QWidget()
        self.tab_Client.setObjectName("tab_Client")
        self.listWidget_Client = QtWidgets.QListWidget(self.tab_Client)
        self.listWidget_Client.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Client.setFont(font)
        self.listWidget_Client.setObjectName("listWidget_Client")
        self.pushButton_Mods_Client_SelectAll = QtWidgets.QPushButton(self.tab_Client)
        self.pushButton_Mods_Client_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Client_SelectAll.setFont(font)
        self.pushButton_Mods_Client_SelectAll.setObjectName("pushButton_Mods_Client_SelectAll")
        self.pushButton_Mods_Client_InvSelect = QtWidgets.QPushButton(self.tab_Client)
        self.pushButton_Mods_Client_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Client_InvSelect.setFont(font)
        self.pushButton_Mods_Client_InvSelect.setObjectName("pushButton_Mods_Client_InvSelect")
        self.label_GFX_Client = QtWidgets.QLabel(self.tab_Client)
        self.label_GFX_Client.setGeometry(QtCore.QRect(370, 130, 101, 101))
        self.label_GFX_Client.setText("")
        self.label_GFX_Client.setPixmap(QtGui.QPixmap("gfx/template.png"))
        self.label_GFX_Client.setScaledContents(True)
        self.label_GFX_Client.setObjectName("label_GFX_Client")
        self.pushButton_Mods_Client_RefreshList = QtWidgets.QPushButton(self.tab_Client)
        self.pushButton_Mods_Client_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Client_RefreshList.setFont(font)
        self.pushButton_Mods_Client_RefreshList.setObjectName("pushButton_Mods_Client_RefreshList")
        self.tabWidget_2.addTab(self.tab_Client, "")
        self.tab_Test = QtWidgets.QWidget()
        self.tab_Test.setObjectName("tab_Test")
        self.listWidget_Test = QtWidgets.QListWidget(self.tab_Test)
        self.listWidget_Test.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Test.setFont(font)
        self.listWidget_Test.setObjectName("listWidget_Test")
        self.pushButton_Mods_Test_SelectAll = QtWidgets.QPushButton(self.tab_Test)
        self.pushButton_Mods_Test_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Test_SelectAll.setFont(font)
        self.pushButton_Mods_Test_SelectAll.setObjectName("pushButton_Mods_Test_SelectAll")
        self.pushButton_Mods_Test_InvSelect = QtWidgets.QPushButton(self.tab_Test)
        self.pushButton_Mods_Test_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Test_InvSelect.setFont(font)
        self.pushButton_Mods_Test_InvSelect.setObjectName("pushButton_Mods_Test_InvSelect")
        self.pushButton_Mods_Test_RefreshList = QtWidgets.QPushButton(self.tab_Test)
        self.pushButton_Mods_Test_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Test_RefreshList.setFont(font)
        self.pushButton_Mods_Test_RefreshList.setObjectName("pushButton_Mods_Test_RefreshList")
        self.label_GFX_Test = QtWidgets.QLabel(self.tab_Test)
        self.label_GFX_Test.setGeometry(QtCore.QRect(370, 130, 101, 101))
        self.label_GFX_Test.setText("")
        self.label_GFX_Test.setPixmap(QtGui.QPixmap("gfx/ampoule.png"))
        self.label_GFX_Test.setScaledContents(True)
        self.label_GFX_Test.setObjectName("label_GFX_Test")
        self.tabWidget_2.addTab(self.tab_Test, "")
        self.tabWidget.addTab(self.Tab_ModsGOS, "")
        self.tab_MODs = QtWidgets.QWidget()
        self.tab_MODs.setObjectName("tab_MODs")
        self.tabWidget_MODs = QtWidgets.QTabWidget(self.tab_MODs)
        self.tabWidget_MODs.setGeometry(QtCore.QRect(10, 10, 481, 451))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget_MODs.setFont(font)
        self.tabWidget_MODs.setObjectName("tabWidget_MODs")
        self.tab_Arma3 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab_Arma3.setFont(font)
        self.tab_Arma3.setObjectName("tab_Arma3")
        self.listWidget_Arma3 = QtWidgets.QListWidget(self.tab_Arma3)
        self.listWidget_Arma3.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Arma3.setFont(font)
        self.listWidget_Arma3.setObjectName("listWidget_Arma3")
        self.pushButton_Mods_A3_InvSelect = QtWidgets.QPushButton(self.tab_Arma3)
        self.pushButton_Mods_A3_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_A3_InvSelect.setFont(font)
        self.pushButton_Mods_A3_InvSelect.setObjectName("pushButton_Mods_A3_InvSelect")
        self.pushButton_Mods_A3_SelectAll = QtWidgets.QPushButton(self.tab_Arma3)
        self.pushButton_Mods_A3_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_A3_SelectAll.setFont(font)
        self.pushButton_Mods_A3_SelectAll.setObjectName("pushButton_Mods_A3_SelectAll")
        self.label_GFX_Arma3 = QtWidgets.QLabel(self.tab_Arma3)
        self.label_GFX_Arma3.setGeometry(QtCore.QRect(370, 130, 101, 101))
        self.label_GFX_Arma3.setText("")
        self.label_GFX_Arma3.setPixmap(QtGui.QPixmap("gfx/template.png"))
        self.label_GFX_Arma3.setScaledContents(True)
        self.label_GFX_Arma3.setObjectName("label_GFX_Arma3")
        self.pushButton_Mods_A3_RefreshList = QtWidgets.QPushButton(self.tab_Arma3)
        self.pushButton_Mods_A3_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_A3_RefreshList.setFont(font)
        self.pushButton_Mods_A3_RefreshList.setObjectName("pushButton_Mods_A3_RefreshList")
        self.tabWidget_MODs.addTab(self.tab_Arma3, "")
        self.tab_Workshop = QtWidgets.QWidget()
        self.tab_Workshop.setObjectName("tab_Workshop")
        self.listWidget_Workshop = QtWidgets.QListWidget(self.tab_Workshop)
        self.listWidget_Workshop.setGeometry(QtCore.QRect(10, 10, 341, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Workshop.setFont(font)
        self.listWidget_Workshop.setObjectName("listWidget_Workshop")
        self.pushButton_Mods_Workshop_RefreshList = QtWidgets.QPushButton(self.tab_Workshop)
        self.pushButton_Mods_Workshop_RefreshList.setGeometry(QtCore.QRect(370, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Workshop_RefreshList.setFont(font)
        self.pushButton_Mods_Workshop_RefreshList.setObjectName("pushButton_Mods_Workshop_RefreshList")
        self.label_GFX_Workshop = QtWidgets.QLabel(self.tab_Workshop)
        self.label_GFX_Workshop.setGeometry(QtCore.QRect(370, 130, 101, 101))
        self.label_GFX_Workshop.setText("")
        self.label_GFX_Workshop.setPixmap(QtGui.QPixmap("gfx/Steam_Icon.png"))
        self.label_GFX_Workshop.setScaledContents(True)
        self.label_GFX_Workshop.setObjectName("label_GFX_Workshop")
        self.pushButton_Mods_Workshop_InvSelect = QtWidgets.QPushButton(self.tab_Workshop)
        self.pushButton_Mods_Workshop_InvSelect.setGeometry(QtCore.QRect(370, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Workshop_InvSelect.setFont(font)
        self.pushButton_Mods_Workshop_InvSelect.setObjectName("pushButton_Mods_Workshop_InvSelect")
        self.pushButton_Mods_Workshop_SelectAll = QtWidgets.QPushButton(self.tab_Workshop)
        self.pushButton_Mods_Workshop_SelectAll.setGeometry(QtCore.QRect(370, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Workshop_SelectAll.setFont(font)
        self.pushButton_Mods_Workshop_SelectAll.setObjectName("pushButton_Mods_Workshop_SelectAll")
        self.tabWidget_MODs.addTab(self.tab_Workshop, "")
        self.tab_DocsArma3 = QtWidgets.QWidget()
        self.tab_DocsArma3.setObjectName("tab_DocsArma3")
        self.tabWidget_MODs.addTab(self.tab_DocsArma3, "")
        self.tab_OthersProfiles = QtWidgets.QWidget()
        self.tab_OthersProfiles.setObjectName("tab_OthersProfiles")
        self.tabWidget_MODs.addTab(self.tab_OthersProfiles, "")
        self.tabWidget.addTab(self.tab_MODs, "")
        self.tab_Options = QtWidgets.QWidget()
        self.tab_Options.setObjectName("tab_Options")
        self.groupBox_Parametre = QtWidgets.QGroupBox(self.tab_Options)
        self.groupBox_Parametre.setGeometry(QtCore.QRect(10, 10, 241, 271))
        self.groupBox_Parametre.setObjectName("groupBox_Parametre")
        self.checkBox_nosplash = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_nosplash.setGeometry(QtCore.QRect(10, 20, 211, 17))
        self.checkBox_nosplash.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_nosplash.setObjectName("checkBox_nosplash")
        self.checkBox_noPause = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_noPause.setGeometry(QtCore.QRect(10, 40, 191, 17))
        self.checkBox_noPause.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_noPause.setObjectName("checkBox_noPause")
        self.checkBox_emptyWorld = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_emptyWorld.setGeometry(QtCore.QRect(10, 60, 211, 17))
        self.checkBox_emptyWorld.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_emptyWorld.setObjectName("checkBox_emptyWorld")
        self.checkBox_showScriptError = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_showScriptError.setGeometry(QtCore.QRect(10, 80, 211, 17))
        self.checkBox_showScriptError.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_showScriptError.setObjectName("checkBox_showScriptError")
        self.checkBox_noCB = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_noCB.setGeometry(QtCore.QRect(10, 100, 191, 17))
        self.checkBox_noCB.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_noCB.setObjectName("checkBox_noCB")
        self.checkBox_xpMode = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_xpMode.setGeometry(QtCore.QRect(10, 120, 221, 17))
        self.checkBox_xpMode.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_xpMode.setObjectName("checkBox_xpMode")
        self.checkBox_AllowFileChange = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_AllowFileChange.setGeometry(QtCore.QRect(10, 140, 211, 17))
        self.checkBox_AllowFileChange.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_AllowFileChange.setObjectName("checkBox_AllowFileChange")
        self.checkBox_noLogs = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_noLogs.setGeometry(QtCore.QRect(10, 160, 191, 17))
        self.checkBox_noLogs.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_noLogs.setObjectName("checkBox_noLogs")
        self.checkBox_customCommand = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_customCommand.setGeometry(QtCore.QRect(10, 180, 61, 17))
        self.checkBox_customCommand.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_customCommand.setObjectName("checkBox_customCommand")
        self.lineEdit_customCommand = QtWidgets.QLineEdit(self.groupBox_Parametre)
        self.lineEdit_customCommand.setEnabled(False)
        self.lineEdit_customCommand.setGeometry(QtCore.QRect(80, 180, 141, 20))
        self.lineEdit_customCommand.setReadOnly(False)
        self.lineEdit_customCommand.setObjectName("lineEdit_customCommand")
        self.tabWidget_options = QtWidgets.QTabWidget(self.tab_Options)
        self.tabWidget_options.setGeometry(QtCore.QRect(10, 290, 491, 161))
        self.tabWidget_options.setObjectName("tabWidget_options")
        self.tab_outilGOS = QtWidgets.QWidget()
        self.tab_outilGOS.setObjectName("tab_outilGOS")
        self.tabWidget_options.addTab(self.tab_outilGOS, "")
        self.tab_GestionProfil = QtWidgets.QWidget()
        self.tab_GestionProfil.setObjectName("tab_GestionProfil")
        self.tabWidget_options.addTab(self.tab_GestionProfil, "")
        self.tab_Langage = QtWidgets.QWidget()
        self.tab_Langage.setObjectName("tab_Langage")
        self.radioButton_language_French = QtWidgets.QRadioButton(self.tab_Langage)
        self.radioButton_language_French.setGeometry(QtCore.QRect(260, 40, 82, 17))
        self.radioButton_language_French.setObjectName("radioButton_language_French")
        self.radioButton_language_English = QtWidgets.QRadioButton(self.tab_Langage)
        self.radioButton_language_English.setGeometry(QtCore.QRect(260, 70, 82, 17))
        self.radioButton_language_English.setObjectName("radioButton_language_English")
        self.label_GFX_Arma3_2 = QtWidgets.QLabel(self.tab_Langage)
        self.label_GFX_Arma3_2.setGeometry(QtCore.QRect(220, 40, 31, 21))
        self.label_GFX_Arma3_2.setText("")
        self.label_GFX_Arma3_2.setPixmap(QtGui.QPixmap("gfx/france.png"))
        self.label_GFX_Arma3_2.setScaledContents(True)
        self.label_GFX_Arma3_2.setObjectName("label_GFX_Arma3_2")
        self.label_GFX_Arma3_3 = QtWidgets.QLabel(self.tab_Langage)
        self.label_GFX_Arma3_3.setGeometry(QtCore.QRect(220, 70, 31, 21))
        self.label_GFX_Arma3_3.setText("")
        self.label_GFX_Arma3_3.setPixmap(QtGui.QPixmap("gfx/royaumeunis.png"))
        self.label_GFX_Arma3_3.setScaledContents(True)
        self.label_GFX_Arma3_3.setObjectName("label_GFX_Arma3_3")
        self.label_GFX_Langage = QtWidgets.QLabel(self.tab_Langage)
        self.label_GFX_Langage.setGeometry(QtCore.QRect(30, 20, 101, 101))
        self.label_GFX_Langage.setText("")
        self.label_GFX_Langage.setPixmap(QtGui.QPixmap("gfx/globe.png"))
        self.label_GFX_Langage.setScaledContents(True)
        self.label_GFX_Langage.setObjectName("label_GFX_Langage")
        self.tabWidget_options.addTab(self.tab_Langage, "")
        self.tab_aPropos = QtWidgets.QWidget()
        self.tab_aPropos.setObjectName("tab_aPropos")
        self.label_GFX_aPropos = QtWidgets.QLabel(self.tab_aPropos)
        self.label_GFX_aPropos.setGeometry(QtCore.QRect(20, 20, 101, 101))
        self.label_GFX_aPropos.setText("")
        self.label_GFX_aPropos.setPixmap(QtGui.QPixmap("gfx/logo-gos.png"))
        self.label_GFX_aPropos.setScaledContents(True)
        self.label_GFX_aPropos.setObjectName("label_GFX_aPropos")
        self.tabWidget_options.addTab(self.tab_aPropos, "")
        self.tabWidget.addTab(self.tab_Options, "")
        self.pushButton_LaunchArma3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_LaunchArma3.setGeometry(QtCore.QRect(420, 560, 81, 41))
        self.pushButton_LaunchArma3.setObjectName("pushButton_LaunchArma3")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("GOS Launcher A3")
        self.label.setObjectName("label")
        self.comboBox_ChoixProfil = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_ChoixProfil.setGeometry(QtCore.QRect(20, 565, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ChoixProfil.setFont(font)
        self.comboBox_ChoixProfil.setObjectName("comboBox_ChoixProfil")
        self.toolButton_saveProfil = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_saveProfil.setGeometry(QtCore.QRect(150, 560, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gfx/disquette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_saveProfil.setIcon(icon1)
        self.toolButton_saveProfil.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_saveProfil.setObjectName("toolButton_saveProfil")
        Fenetre_Principale.setCentralWidget(self.centralWidget)

        self.retranslateUi(Fenetre_Principale)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_MODs.setCurrentIndex(0)
        self.tabWidget_options.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Fenetre_Principale)

    def retranslateUi(self, Fenetre_Principale):
        _translate = QtCore.QCoreApplication.translate
        Fenetre_Principale.setWindowTitle(_translate("Fenetre_Principale", "GOS Launcher A3"))
        self.pushButton_Mods_Template_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Template_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Template_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Template), _translate("Fenetre_Principale", "TEMPLATE"))
        self.pushButton_Mods_Framework_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Framework_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Framework_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Framework), _translate("Fenetre_Principale", "FRAMEWORK"))
        self.pushButton_Mods_Islands_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Islands_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Islands_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Islands), _translate("Fenetre_Principale", "ISLANDS"))
        self.pushButton_Mods_Units_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Units_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Units_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Units), _translate("Fenetre_Principale", "UNITS"))
        self.pushButton_Mods_Materiel_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Materiel_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Materiel_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Materiel), _translate("Fenetre_Principale", "MATERIEL"))
        self.pushButton_Mods_Client_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Client_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Client_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Client), _translate("Fenetre_Principale", "CLIENT"))
        self.pushButton_Mods_Test_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Test_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Test_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_Test), _translate("Fenetre_Principale", "TEST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_ModsGOS), _translate("Fenetre_Principale", "Mods GOS"))
        self.pushButton_Mods_A3_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_A3_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_A3_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_Arma3), _translate("Fenetre_Principale", "ARMA3"))
        self.pushButton_Mods_Workshop_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Workshop_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Workshop_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_Workshop), _translate("Fenetre_Principale", "WorkShop"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_DocsArma3), _translate("Fenetre_Principale", "Default Profile"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_OthersProfiles), _translate("Fenetre_Principale", "ARMA 3 Others Profile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MODs), _translate("Fenetre_Principale", "MODs"))
        self.groupBox_Parametre.setTitle(_translate("Fenetre_Principale", "Paramètres"))
        self.checkBox_nosplash.setText(_translate("Fenetre_Principale", "Passer écrans de démarrage"))
        self.checkBox_noPause.setText(_translate("Fenetre_Principale", "Pas de pause"))
        self.checkBox_emptyWorld.setText(_translate("Fenetre_Principale", "Monde vide au demarrage"))
        self.checkBox_showScriptError.setText(_translate("Fenetre_Principale", "Afficher les erreurs scripts"))
        self.checkBox_noCB.setText(_translate("Fenetre_Principale", "Arret gestion Multi-Core"))
        self.checkBox_xpMode.setText(_translate("Fenetre_Principale", "mode winXP/multi GPU/DirectX9"))
        self.checkBox_AllowFileChange.setText(_translate("Fenetre_Principale", "Activer Modification du Fichier"))
        self.checkBox_noLogs.setText(_translate("Fenetre_Principale", "no logs"))
        self.checkBox_customCommand.setText(_translate("Fenetre_Principale", "custom"))
        self.lineEdit_customCommand.setPlaceholderText(_translate("Fenetre_Principale", "ligne de commande..."))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_outilGOS), _translate("Fenetre_Principale", "Outils GOS"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_GestionProfil), _translate("Fenetre_Principale", "Profils"))
        self.radioButton_language_French.setText(_translate("Fenetre_Principale", "Français"))
        self.radioButton_language_English.setText(_translate("Fenetre_Principale", "Anglais"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_Langage), _translate("Fenetre_Principale", "Langage"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_aPropos), _translate("Fenetre_Principale", "A propos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Options), _translate("Fenetre_Principale", "Options"))
        self.pushButton_LaunchArma3.setText(_translate("Fenetre_Principale", "Lancer\n"
"Arma 3"))
        self.toolButton_saveProfil.setText(_translate("Fenetre_Principale", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fenetre_Principale = QtWidgets.QMainWindow()
    ui = Ui_Fenetre_Principale()
    ui.setupUi(Fenetre_Principale)
    Fenetre_Principale.show()
    sys.exit(app.exec_())

