# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Zone Documents\ToF\Documents\GitHub\GOSLauncher_A3_Python_version\principale.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fenetre_Principale(object):
    def setupUi(self, Fenetre_Principale):
        Fenetre_Principale.setObjectName("Fenetre_Principale")
        Fenetre_Principale.resize(587, 658)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gfx/GOSLauncherA3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Fenetre_Principale.setWindowIcon(icon)
        Fenetre_Principale.setStyleSheet("background-color: rgb(236, 236, 236);")
        Fenetre_Principale.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralWidget = QtWidgets.QWidget(Fenetre_Principale)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget_synchro = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_synchro.setGeometry(QtCore.QRect(10, 55, 571, 501))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget_synchro.setFont(font)
        self.tabWidget_synchro.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.tabWidget_synchro.setObjectName("tabWidget_synchro")
        self.Tab_ModsGOS = QtWidgets.QWidget()
        self.Tab_ModsGOS.setObjectName("Tab_ModsGOS")
        self.tabWidget_GOS = QtWidgets.QTabWidget(self.Tab_ModsGOS)
        self.tabWidget_GOS.setGeometry(QtCore.QRect(5, 10, 551, 461))
        self.tabWidget_GOS.setMinimumSize(QtCore.QSize(551, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setKerning(True)
        self.tabWidget_GOS.setFont(font)
        self.tabWidget_GOS.setAutoFillBackground(False)
        self.tabWidget_GOS.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_GOS.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_GOS.setUsesScrollButtons(True)
        self.tabWidget_GOS.setDocumentMode(False)
        self.tabWidget_GOS.setTabBarAutoHide(False)
        self.tabWidget_GOS.setObjectName("tabWidget_GOS")
        self.tab_Template = QtWidgets.QWidget()
        self.tab_Template.setObjectName("tab_Template")
        self.listWidget_Template = QtWidgets.QListWidget(self.tab_Template)
        self.listWidget_Template.setGeometry(QtCore.QRect(10, 10, 396, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Template.setFont(font)
        self.listWidget_Template.setStyleSheet("")
        self.listWidget_Template.setObjectName("listWidget_Template")
        self.pushButton_Mods_Template_RefreshList = QtWidgets.QPushButton(self.tab_Template)
        self.pushButton_Mods_Template_RefreshList.setGeometry(QtCore.QRect(425, 365, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Template_RefreshList.setFont(font)
        self.pushButton_Mods_Template_RefreshList.setObjectName("pushButton_Mods_Template_RefreshList")
        self.pushButton_Mods_Template_InvSelect = QtWidgets.QPushButton(self.tab_Template)
        self.pushButton_Mods_Template_InvSelect.setGeometry(QtCore.QRect(425, 65, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Template_InvSelect.setFont(font)
        self.pushButton_Mods_Template_InvSelect.setObjectName("pushButton_Mods_Template_InvSelect")
        self.pushButton_Mods_Template_SelectAll = QtWidgets.QPushButton(self.tab_Template)
        self.pushButton_Mods_Template_SelectAll.setGeometry(QtCore.QRect(425, 15, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Template_SelectAll.setFont(font)
        self.pushButton_Mods_Template_SelectAll.setObjectName("pushButton_Mods_Template_SelectAll")
        self.label_GFX_Template = QtWidgets.QLabel(self.tab_Template)
        self.label_GFX_Template.setGeometry(QtCore.QRect(425, 185, 101, 101))
        self.label_GFX_Template.setText("")
        self.label_GFX_Template.setPixmap(QtGui.QPixmap("gfx/logo-gos.png"))
        self.label_GFX_Template.setScaledContents(True)
        self.label_GFX_Template.setObjectName("label_GFX_Template")
        self.comboBox_ChoixApparence = QtWidgets.QComboBox(self.tab_Template)
        self.comboBox_ChoixApparence.setGeometry(QtCore.QRect(415, 135, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ChoixApparence.setFont(font)
        self.comboBox_ChoixApparence.setObjectName("comboBox_ChoixApparence")
        self.tabWidget_GOS.addTab(self.tab_Template, "")
        self.tab_Framework = QtWidgets.QWidget()
        self.tab_Framework.setObjectName("tab_Framework")
        self.listWidget_Framework = QtWidgets.QListWidget(self.tab_Framework)
        self.listWidget_Framework.setGeometry(QtCore.QRect(10, 10, 406, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Framework.setFont(font)
        self.listWidget_Framework.setObjectName("listWidget_Framework")
        self.pushButton_Mods_Framework_SelectAll = QtWidgets.QPushButton(self.tab_Framework)
        self.pushButton_Mods_Framework_SelectAll.setGeometry(QtCore.QRect(435, 15, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Framework_SelectAll.setFont(font)
        self.pushButton_Mods_Framework_SelectAll.setObjectName("pushButton_Mods_Framework_SelectAll")
        self.pushButton_Mods_Framework_RefreshList = QtWidgets.QPushButton(self.tab_Framework)
        self.pushButton_Mods_Framework_RefreshList.setGeometry(QtCore.QRect(435, 245, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Framework_RefreshList.setFont(font)
        self.pushButton_Mods_Framework_RefreshList.setObjectName("pushButton_Mods_Framework_RefreshList")
        self.label_GFX_Framework = QtWidgets.QLabel(self.tab_Framework)
        self.label_GFX_Framework.setGeometry(QtCore.QRect(435, 135, 101, 91))
        self.label_GFX_Framework.setText("")
        self.label_GFX_Framework.setPixmap(QtGui.QPixmap("gfx/atelier.png"))
        self.label_GFX_Framework.setScaledContents(True)
        self.label_GFX_Framework.setObjectName("label_GFX_Framework")
        self.pushButton_Mods_Framework_InvSelect = QtWidgets.QPushButton(self.tab_Framework)
        self.pushButton_Mods_Framework_InvSelect.setGeometry(QtCore.QRect(435, 65, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Framework_InvSelect.setFont(font)
        self.pushButton_Mods_Framework_InvSelect.setObjectName("pushButton_Mods_Framework_InvSelect")
        self.tabWidget_GOS.addTab(self.tab_Framework, "")
        self.tab_Islands = QtWidgets.QWidget()
        self.tab_Islands.setObjectName("tab_Islands")
        self.listWidget_Islands = QtWidgets.QListWidget(self.tab_Islands)
        self.listWidget_Islands.setGeometry(QtCore.QRect(10, 10, 411, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Islands.setFont(font)
        self.listWidget_Islands.setObjectName("listWidget_Islands")
        self.pushButton_Mods_Islands_SelectAll = QtWidgets.QPushButton(self.tab_Islands)
        self.pushButton_Mods_Islands_SelectAll.setGeometry(QtCore.QRect(435, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Islands_SelectAll.setFont(font)
        self.pushButton_Mods_Islands_SelectAll.setObjectName("pushButton_Mods_Islands_SelectAll")
        self.pushButton_Mods_Islands_InvSelect = QtWidgets.QPushButton(self.tab_Islands)
        self.pushButton_Mods_Islands_InvSelect.setGeometry(QtCore.QRect(435, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Islands_InvSelect.setFont(font)
        self.pushButton_Mods_Islands_InvSelect.setObjectName("pushButton_Mods_Islands_InvSelect")
        self.label_GFX_Islands = QtWidgets.QLabel(self.tab_Islands)
        self.label_GFX_Islands.setGeometry(QtCore.QRect(435, 130, 101, 101))
        self.label_GFX_Islands.setText("")
        self.label_GFX_Islands.setPixmap(QtGui.QPixmap("gfx/IslandStone.png"))
        self.label_GFX_Islands.setScaledContents(True)
        self.label_GFX_Islands.setObjectName("label_GFX_Islands")
        self.pushButton_Mods_Islands_RefreshList = QtWidgets.QPushButton(self.tab_Islands)
        self.pushButton_Mods_Islands_RefreshList.setGeometry(QtCore.QRect(435, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Islands_RefreshList.setFont(font)
        self.pushButton_Mods_Islands_RefreshList.setObjectName("pushButton_Mods_Islands_RefreshList")
        self.tabWidget_GOS.addTab(self.tab_Islands, "")
        self.tab_Units = QtWidgets.QWidget()
        self.tab_Units.setObjectName("tab_Units")
        self.listWidget_Units = QtWidgets.QListWidget(self.tab_Units)
        self.listWidget_Units.setGeometry(QtCore.QRect(10, 10, 401, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Units.setFont(font)
        self.listWidget_Units.setObjectName("listWidget_Units")
        self.label_GFX_Units = QtWidgets.QLabel(self.tab_Units)
        self.label_GFX_Units.setGeometry(QtCore.QRect(420, 150, 101, 81))
        self.label_GFX_Units.setText("")
        self.label_GFX_Units.setPixmap(QtGui.QPixmap("gfx/units.png"))
        self.label_GFX_Units.setScaledContents(True)
        self.label_GFX_Units.setObjectName("label_GFX_Units")
        self.pushButton_Mods_Units_InvSelect = QtWidgets.QPushButton(self.tab_Units)
        self.pushButton_Mods_Units_InvSelect.setGeometry(QtCore.QRect(430, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Units_InvSelect.setFont(font)
        self.pushButton_Mods_Units_InvSelect.setObjectName("pushButton_Mods_Units_InvSelect")
        self.pushButton_Mods_Units_RefreshList = QtWidgets.QPushButton(self.tab_Units)
        self.pushButton_Mods_Units_RefreshList.setGeometry(QtCore.QRect(430, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Units_RefreshList.setFont(font)
        self.pushButton_Mods_Units_RefreshList.setObjectName("pushButton_Mods_Units_RefreshList")
        self.pushButton_Mods_Units_SelectAll = QtWidgets.QPushButton(self.tab_Units)
        self.pushButton_Mods_Units_SelectAll.setGeometry(QtCore.QRect(430, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Units_SelectAll.setFont(font)
        self.pushButton_Mods_Units_SelectAll.setObjectName("pushButton_Mods_Units_SelectAll")
        self.tabWidget_GOS.addTab(self.tab_Units, "")
        self.tab_Materiel = QtWidgets.QWidget()
        self.tab_Materiel.setObjectName("tab_Materiel")
        self.listWidget_Materiel = QtWidgets.QListWidget(self.tab_Materiel)
        self.listWidget_Materiel.setGeometry(QtCore.QRect(10, 10, 421, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Materiel.setFont(font)
        self.listWidget_Materiel.setObjectName("listWidget_Materiel")
        self.pushButton_Mods_Materiel_SelectAll = QtWidgets.QPushButton(self.tab_Materiel)
        self.pushButton_Mods_Materiel_SelectAll.setGeometry(QtCore.QRect(440, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Materiel_SelectAll.setFont(font)
        self.pushButton_Mods_Materiel_SelectAll.setObjectName("pushButton_Mods_Materiel_SelectAll")
        self.label_GFX_Materiel = QtWidgets.QLabel(self.tab_Materiel)
        self.label_GFX_Materiel.setGeometry(QtCore.QRect(440, 130, 101, 101))
        self.label_GFX_Materiel.setText("")
        self.label_GFX_Materiel.setPixmap(QtGui.QPixmap("gfx/hangar.png"))
        self.label_GFX_Materiel.setScaledContents(True)
        self.label_GFX_Materiel.setObjectName("label_GFX_Materiel")
        self.pushButton_Mods_Materiel_RefreshList = QtWidgets.QPushButton(self.tab_Materiel)
        self.pushButton_Mods_Materiel_RefreshList.setGeometry(QtCore.QRect(440, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Materiel_RefreshList.setFont(font)
        self.pushButton_Mods_Materiel_RefreshList.setObjectName("pushButton_Mods_Materiel_RefreshList")
        self.pushButton_Mods_Materiel_InvSelect = QtWidgets.QPushButton(self.tab_Materiel)
        self.pushButton_Mods_Materiel_InvSelect.setGeometry(QtCore.QRect(440, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Materiel_InvSelect.setFont(font)
        self.pushButton_Mods_Materiel_InvSelect.setObjectName("pushButton_Mods_Materiel_InvSelect")
        self.tabWidget_GOS.addTab(self.tab_Materiel, "")
        self.tab_Client = QtWidgets.QWidget()
        self.tab_Client.setObjectName("tab_Client")
        self.listWidget_Client = QtWidgets.QListWidget(self.tab_Client)
        self.listWidget_Client.setGeometry(QtCore.QRect(10, 10, 411, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Client.setFont(font)
        self.listWidget_Client.setObjectName("listWidget_Client")
        self.pushButton_Mods_Client_SelectAll = QtWidgets.QPushButton(self.tab_Client)
        self.pushButton_Mods_Client_SelectAll.setGeometry(QtCore.QRect(430, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Client_SelectAll.setFont(font)
        self.pushButton_Mods_Client_SelectAll.setObjectName("pushButton_Mods_Client_SelectAll")
        self.pushButton_Mods_Client_InvSelect = QtWidgets.QPushButton(self.tab_Client)
        self.pushButton_Mods_Client_InvSelect.setGeometry(QtCore.QRect(430, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Client_InvSelect.setFont(font)
        self.pushButton_Mods_Client_InvSelect.setObjectName("pushButton_Mods_Client_InvSelect")
        self.label_GFX_Client = QtWidgets.QLabel(self.tab_Client)
        self.label_GFX_Client.setGeometry(QtCore.QRect(430, 130, 101, 101))
        self.label_GFX_Client.setText("")
        self.label_GFX_Client.setPixmap(QtGui.QPixmap("gfx/template.png"))
        self.label_GFX_Client.setScaledContents(True)
        self.label_GFX_Client.setObjectName("label_GFX_Client")
        self.pushButton_Mods_Client_RefreshList = QtWidgets.QPushButton(self.tab_Client)
        self.pushButton_Mods_Client_RefreshList.setGeometry(QtCore.QRect(430, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Client_RefreshList.setFont(font)
        self.pushButton_Mods_Client_RefreshList.setObjectName("pushButton_Mods_Client_RefreshList")
        self.tabWidget_GOS.addTab(self.tab_Client, "")
        self.tab_Test = QtWidgets.QWidget()
        self.tab_Test.setObjectName("tab_Test")
        self.listWidget_Test = QtWidgets.QListWidget(self.tab_Test)
        self.listWidget_Test.setGeometry(QtCore.QRect(10, 10, 401, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Test.setFont(font)
        self.listWidget_Test.setObjectName("listWidget_Test")
        self.pushButton_Mods_Test_SelectAll = QtWidgets.QPushButton(self.tab_Test)
        self.pushButton_Mods_Test_SelectAll.setGeometry(QtCore.QRect(430, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Test_SelectAll.setFont(font)
        self.pushButton_Mods_Test_SelectAll.setObjectName("pushButton_Mods_Test_SelectAll")
        self.pushButton_Mods_Test_InvSelect = QtWidgets.QPushButton(self.tab_Test)
        self.pushButton_Mods_Test_InvSelect.setGeometry(QtCore.QRect(430, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Test_InvSelect.setFont(font)
        self.pushButton_Mods_Test_InvSelect.setObjectName("pushButton_Mods_Test_InvSelect")
        self.pushButton_Mods_Test_RefreshList = QtWidgets.QPushButton(self.tab_Test)
        self.pushButton_Mods_Test_RefreshList.setGeometry(QtCore.QRect(430, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Test_RefreshList.setFont(font)
        self.pushButton_Mods_Test_RefreshList.setObjectName("pushButton_Mods_Test_RefreshList")
        self.label_GFX_Test = QtWidgets.QLabel(self.tab_Test)
        self.label_GFX_Test.setGeometry(QtCore.QRect(430, 130, 101, 101))
        self.label_GFX_Test.setText("")
        self.label_GFX_Test.setPixmap(QtGui.QPixmap("gfx/ampoule.png"))
        self.label_GFX_Test.setScaledContents(True)
        self.label_GFX_Test.setObjectName("label_GFX_Test")
        self.tabWidget_GOS.addTab(self.tab_Test, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_Mods_Interclan_SelectAll = QtWidgets.QPushButton(self.tab)
        self.pushButton_Mods_Interclan_SelectAll.setGeometry(QtCore.QRect(430, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Interclan_SelectAll.setFont(font)
        self.pushButton_Mods_Interclan_SelectAll.setObjectName("pushButton_Mods_Interclan_SelectAll")
        self.listWidget_Interclan = QtWidgets.QListWidget(self.tab)
        self.listWidget_Interclan.setGeometry(QtCore.QRect(10, 10, 401, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Interclan.setFont(font)
        self.listWidget_Interclan.setObjectName("listWidget_Interclan")
        self.pushButton_Mods_Interclan_RefreshList = QtWidgets.QPushButton(self.tab)
        self.pushButton_Mods_Interclan_RefreshList.setGeometry(QtCore.QRect(430, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Interclan_RefreshList.setFont(font)
        self.pushButton_Mods_Interclan_RefreshList.setObjectName("pushButton_Mods_Interclan_RefreshList")
        self.label_GFX_Interclan = QtWidgets.QLabel(self.tab)
        self.label_GFX_Interclan.setGeometry(QtCore.QRect(430, 130, 101, 101))
        self.label_GFX_Interclan.setText("")
        self.label_GFX_Interclan.setPixmap(QtGui.QPixmap("gfx/globe.png"))
        self.label_GFX_Interclan.setScaledContents(True)
        self.label_GFX_Interclan.setObjectName("label_GFX_Interclan")
        self.pushButton_Mods_Interclan_InvSelect = QtWidgets.QPushButton(self.tab)
        self.pushButton_Mods_Interclan_InvSelect.setGeometry(QtCore.QRect(430, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Interclan_InvSelect.setFont(font)
        self.pushButton_Mods_Interclan_InvSelect.setObjectName("pushButton_Mods_Interclan_InvSelect")
        self.tabWidget_GOS.addTab(self.tab, "")
        self.tabWidget_synchro.addTab(self.Tab_ModsGOS, "")
        self.tab_MODs = QtWidgets.QWidget()
        self.tab_MODs.setObjectName("tab_MODs")
        self.tabWidget_MODs = QtWidgets.QTabWidget(self.tab_MODs)
        self.tabWidget_MODs.setGeometry(QtCore.QRect(10, 10, 551, 451))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget_MODs.setFont(font)
        self.tabWidget_MODs.setObjectName("tabWidget_MODs")
        self.tab_Arma3 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab_Arma3.setFont(font)
        self.tab_Arma3.setObjectName("tab_Arma3")
        self.listWidget_Arma3 = QtWidgets.QListWidget(self.tab_Arma3)
        self.listWidget_Arma3.setGeometry(QtCore.QRect(10, 10, 411, 411))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Arma3.setFont(font)
        self.listWidget_Arma3.setObjectName("listWidget_Arma3")
        self.pushButton_Mods_A3_InvSelect = QtWidgets.QPushButton(self.tab_Arma3)
        self.pushButton_Mods_A3_InvSelect.setGeometry(QtCore.QRect(430, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_A3_InvSelect.setFont(font)
        self.pushButton_Mods_A3_InvSelect.setObjectName("pushButton_Mods_A3_InvSelect")
        self.pushButton_Mods_A3_SelectAll = QtWidgets.QPushButton(self.tab_Arma3)
        self.pushButton_Mods_A3_SelectAll.setGeometry(QtCore.QRect(430, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_A3_SelectAll.setFont(font)
        self.pushButton_Mods_A3_SelectAll.setObjectName("pushButton_Mods_A3_SelectAll")
        self.label_GFX_Arma3 = QtWidgets.QLabel(self.tab_Arma3)
        self.label_GFX_Arma3.setGeometry(QtCore.QRect(430, 130, 101, 101))
        self.label_GFX_Arma3.setText("")
        self.label_GFX_Arma3.setPixmap(QtGui.QPixmap("gfx/template.png"))
        self.label_GFX_Arma3.setScaledContents(True)
        self.label_GFX_Arma3.setObjectName("label_GFX_Arma3")
        self.pushButton_Mods_A3_RefreshList = QtWidgets.QPushButton(self.tab_Arma3)
        self.pushButton_Mods_A3_RefreshList.setGeometry(QtCore.QRect(430, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_A3_RefreshList.setFont(font)
        self.pushButton_Mods_A3_RefreshList.setObjectName("pushButton_Mods_A3_RefreshList")
        self.tabWidget_MODs.addTab(self.tab_Arma3, "")
        self.tab_Workshop = QtWidgets.QWidget()
        self.tab_Workshop.setObjectName("tab_Workshop")
        self.listWidget_Workshop = QtWidgets.QListWidget(self.tab_Workshop)
        self.listWidget_Workshop.setGeometry(QtCore.QRect(10, 10, 411, 401))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_Workshop.setFont(font)
        self.listWidget_Workshop.setObjectName("listWidget_Workshop")
        self.pushButton_Mods_Workshop_RefreshList = QtWidgets.QPushButton(self.tab_Workshop)
        self.pushButton_Mods_Workshop_RefreshList.setGeometry(QtCore.QRect(430, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Workshop_RefreshList.setFont(font)
        self.pushButton_Mods_Workshop_RefreshList.setObjectName("pushButton_Mods_Workshop_RefreshList")
        self.label_GFX_Workshop = QtWidgets.QLabel(self.tab_Workshop)
        self.label_GFX_Workshop.setGeometry(QtCore.QRect(430, 130, 101, 101))
        self.label_GFX_Workshop.setText("")
        self.label_GFX_Workshop.setPixmap(QtGui.QPixmap("gfx/Steam_Icon.png"))
        self.label_GFX_Workshop.setScaledContents(True)
        self.label_GFX_Workshop.setObjectName("label_GFX_Workshop")
        self.pushButton_Mods_Workshop_InvSelect = QtWidgets.QPushButton(self.tab_Workshop)
        self.pushButton_Mods_Workshop_InvSelect.setGeometry(QtCore.QRect(430, 70, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Workshop_InvSelect.setFont(font)
        self.pushButton_Mods_Workshop_InvSelect.setObjectName("pushButton_Mods_Workshop_InvSelect")
        self.pushButton_Mods_Workshop_SelectAll = QtWidgets.QPushButton(self.tab_Workshop)
        self.pushButton_Mods_Workshop_SelectAll.setGeometry(QtCore.QRect(430, 20, 101, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mods_Workshop_SelectAll.setFont(font)
        self.pushButton_Mods_Workshop_SelectAll.setObjectName("pushButton_Mods_Workshop_SelectAll")
        self.tabWidget_MODs.addTab(self.tab_Workshop, "")
        self.tab_DocsArma3 = QtWidgets.QWidget()
        self.tab_DocsArma3.setObjectName("tab_DocsArma3")
        self.tabWidget_MODs.addTab(self.tab_DocsArma3, "")
        self.tab_OthersProfiles = QtWidgets.QWidget()
        self.tab_OthersProfiles.setObjectName("tab_OthersProfiles")
        self.tabWidget_MODs.addTab(self.tab_OthersProfiles, "")
        self.tabWidget_synchro.addTab(self.tab_MODs, "")
        self.tab_priorityList = QtWidgets.QWidget()
        self.tab_priorityList.setObjectName("tab_priorityList")
        self.listWidget_priority = QtWidgets.QListWidget(self.tab_priorityList)
        self.listWidget_priority.setGeometry(QtCore.QRect(10, 10, 361, 446))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.listWidget_priority.setFont(font)
        self.listWidget_priority.setObjectName("listWidget_priority")
        self.pushButton_priorityTop = QtWidgets.QPushButton(self.tab_priorityList)
        self.pushButton_priorityTop.setGeometry(QtCore.QRect(390, 25, 91, 41))
        self.pushButton_priorityTop.setObjectName("pushButton_priorityTop")
        self.pushButton_priorityPlus = QtWidgets.QPushButton(self.tab_priorityList)
        self.pushButton_priorityPlus.setGeometry(QtCore.QRect(390, 75, 91, 41))
        self.pushButton_priorityPlus.setObjectName("pushButton_priorityPlus")
        self.pushButton_priorityMinus = QtWidgets.QPushButton(self.tab_priorityList)
        self.pushButton_priorityMinus.setGeometry(QtCore.QRect(390, 125, 91, 41))
        self.pushButton_priorityMinus.setObjectName("pushButton_priorityMinus")
        self.pushButton_priorityBottom = QtWidgets.QPushButton(self.tab_priorityList)
        self.pushButton_priorityBottom.setGeometry(QtCore.QRect(390, 180, 91, 41))
        self.pushButton_priorityBottom.setObjectName("pushButton_priorityBottom")
        self.tabWidget_synchro.addTab(self.tab_priorityList, "")
        self.tab_Options = QtWidgets.QWidget()
        self.tab_Options.setObjectName("tab_Options")
        self.groupBox_Parametre = QtWidgets.QGroupBox(self.tab_Options)
        self.groupBox_Parametre.setGeometry(QtCore.QRect(10, 10, 271, 301))
        self.groupBox_Parametre.setObjectName("groupBox_Parametre")
        self.checkBox_nosplash = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_nosplash.setGeometry(QtCore.QRect(10, 20, 211, 17))
        self.checkBox_nosplash.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_nosplash.setObjectName("checkBox_nosplash")
        self.checkBox_noPause = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_noPause.setGeometry(QtCore.QRect(10, 40, 191, 17))
        self.checkBox_noPause.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_noPause.setObjectName("checkBox_noPause")
        self.checkBox_emptyWorld = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_emptyWorld.setGeometry(QtCore.QRect(10, 60, 211, 17))
        self.checkBox_emptyWorld.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_emptyWorld.setObjectName("checkBox_emptyWorld")
        self.checkBox_showScriptError = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_showScriptError.setGeometry(QtCore.QRect(10, 80, 211, 17))
        self.checkBox_showScriptError.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_showScriptError.setObjectName("checkBox_showScriptError")
        self.checkBox_noCB = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_noCB.setGeometry(QtCore.QRect(10, 100, 191, 17))
        self.checkBox_noCB.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_noCB.setObjectName("checkBox_noCB")
        self.checkBox_AllowFileChange = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_AllowFileChange.setGeometry(QtCore.QRect(10, 120, 211, 17))
        self.checkBox_AllowFileChange.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_AllowFileChange.setObjectName("checkBox_AllowFileChange")
        self.checkBox_noLogs = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_noLogs.setGeometry(QtCore.QRect(10, 140, 191, 17))
        self.checkBox_noLogs.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_noLogs.setObjectName("checkBox_noLogs")
        self.checkBox_customCommand = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_customCommand.setEnabled(True)
        self.checkBox_customCommand.setGeometry(QtCore.QRect(10, 160, 61, 17))
        self.checkBox_customCommand.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_customCommand.setObjectName("checkBox_customCommand")
        self.lineEdit_customCommand = QtWidgets.QLineEdit(self.groupBox_Parametre)
        self.lineEdit_customCommand.setEnabled(False)
        self.lineEdit_customCommand.setGeometry(QtCore.QRect(80, 160, 141, 20))
        self.lineEdit_customCommand.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_customCommand.setReadOnly(False)
        self.lineEdit_customCommand.setObjectName("lineEdit_customCommand")
        self.checkBox_windowedMode = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_windowedMode.setEnabled(True)
        self.checkBox_windowedMode.setGeometry(QtCore.QRect(10, 180, 101, 17))
        self.checkBox_windowedMode.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_windowedMode.setObjectName("checkBox_windowedMode")
        self.label_optionsXwindow = QtWidgets.QLabel(self.groupBox_Parametre)
        self.label_optionsXwindow.setGeometry(QtCore.QRect(30, 200, 21, 16))
        self.label_optionsXwindow.setObjectName("label_optionsXwindow")
        self.label_optionsYwindow = QtWidgets.QLabel(self.groupBox_Parametre)
        self.label_optionsYwindow.setGeometry(QtCore.QRect(120, 200, 21, 16))
        self.label_optionsYwindow.setObjectName("label_optionsYwindow")
        self.lineEdit_WindowedModeX = QtWidgets.QLineEdit(self.groupBox_Parametre)
        self.lineEdit_WindowedModeX.setEnabled(False)
        self.lineEdit_WindowedModeX.setGeometry(QtCore.QRect(50, 200, 51, 20))
        self.lineEdit_WindowedModeX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_WindowedModeX.setMaxLength(4)
        self.lineEdit_WindowedModeX.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_WindowedModeX.setReadOnly(False)
        self.lineEdit_WindowedModeX.setPlaceholderText("")
        self.lineEdit_WindowedModeX.setObjectName("lineEdit_WindowedModeX")
        self.lineEdit_WindowedModeY = QtWidgets.QLineEdit(self.groupBox_Parametre)
        self.lineEdit_WindowedModeY.setEnabled(False)
        self.lineEdit_WindowedModeY.setGeometry(QtCore.QRect(140, 200, 51, 20))
        self.lineEdit_WindowedModeY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_WindowedModeY.setMaxLength(4)
        self.lineEdit_WindowedModeY.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_WindowedModeY.setReadOnly(False)
        self.lineEdit_WindowedModeY.setPlaceholderText("")
        self.lineEdit_WindowedModeY.setObjectName("lineEdit_WindowedModeY")
        self.checkBox_arma3_64bit = QtWidgets.QCheckBox(self.groupBox_Parametre)
        self.checkBox_arma3_64bit.setGeometry(QtCore.QRect(10, 225, 101, 17))
        self.checkBox_arma3_64bit.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_arma3_64bit.setObjectName("checkBox_arma3_64bit")
        self.tabWidget_options = QtWidgets.QTabWidget(self.tab_Options)
        self.tabWidget_options.setGeometry(QtCore.QRect(5, 320, 551, 151))
        self.tabWidget_options.setObjectName("tabWidget_options")
        self.tab_outilGOS = QtWidgets.QWidget()
        self.tab_outilGOS.setObjectName("tab_outilGOS")
        self.tabWidget_options.addTab(self.tab_outilGOS, "")
        self.tab_GestionProfil = QtWidgets.QWidget()
        self.tab_GestionProfil.setObjectName("tab_GestionProfil")
        self.label_GFX_Langage_2 = QtWidgets.QLabel(self.tab_GestionProfil)
        self.label_GFX_Langage_2.setGeometry(QtCore.QRect(20, 25, 71, 76))
        self.label_GFX_Langage_2.setText("")
        self.label_GFX_Langage_2.setPixmap(QtGui.QPixmap("gfx/profil.png"))
        self.label_GFX_Langage_2.setScaledContents(True)
        self.label_GFX_Langage_2.setObjectName("label_GFX_Langage_2")
        self.listWidget_profil = QtWidgets.QListWidget(self.tab_GestionProfil)
        self.listWidget_profil.setGeometry(QtCore.QRect(110, 5, 391, 71))
        self.listWidget_profil.setObjectName("listWidget_profil")
        self.lineEdit_AddProfilName = QtWidgets.QLineEdit(self.tab_GestionProfil)
        self.lineEdit_AddProfilName.setGeometry(QtCore.QRect(240, 80, 161, 20))
        self.lineEdit_AddProfilName.setAutoFillBackground(False)
        self.lineEdit_AddProfilName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_AddProfilName.setObjectName("lineEdit_AddProfilName")
        self.label_addAProfil = QtWidgets.QLabel(self.tab_GestionProfil)
        self.label_addAProfil.setGeometry(QtCore.QRect(110, 80, 111, 21))
        self.label_addAProfil.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_addAProfil.setObjectName("label_addAProfil")
        self.pushButton_AddProfil = QtWidgets.QPushButton(self.tab_GestionProfil)
        self.pushButton_AddProfil.setGeometry(QtCore.QRect(410, 80, 31, 21))
        self.pushButton_AddProfil.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gfx/ajouter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_AddProfil.setIcon(icon1)
        self.pushButton_AddProfil.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_AddProfil.setFlat(True)
        self.pushButton_AddProfil.setObjectName("pushButton_AddProfil")
        self.pushButton_copyProfil = QtWidgets.QPushButton(self.tab_GestionProfil)
        self.pushButton_copyProfil.setGeometry(QtCore.QRect(510, -5, 26, 31))
        self.pushButton_copyProfil.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gfx/copier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_copyProfil.setIcon(icon2)
        self.pushButton_copyProfil.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_copyProfil.setFlat(True)
        self.pushButton_copyProfil.setObjectName("pushButton_copyProfil")
        self.pushButton_renameProfil = QtWidgets.QPushButton(self.tab_GestionProfil)
        self.pushButton_renameProfil.setGeometry(QtCore.QRect(510, 20, 26, 26))
        self.pushButton_renameProfil.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gfx/rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_renameProfil.setIcon(icon3)
        self.pushButton_renameProfil.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_renameProfil.setFlat(True)
        self.pushButton_renameProfil.setObjectName("pushButton_renameProfil")
        self.pushButton_favorisProfil = QtWidgets.QPushButton(self.tab_GestionProfil)
        self.pushButton_favorisProfil.setGeometry(QtCore.QRect(510, 45, 26, 26))
        self.pushButton_favorisProfil.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gfx/favoris.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_favorisProfil.setIcon(icon4)
        self.pushButton_favorisProfil.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_favorisProfil.setFlat(True)
        self.pushButton_favorisProfil.setObjectName("pushButton_favorisProfil")
        self.pushButton_deleteProfil = QtWidgets.QPushButton(self.tab_GestionProfil)
        self.pushButton_deleteProfil.setGeometry(QtCore.QRect(510, 70, 26, 26))
        self.pushButton_deleteProfil.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gfx/supprimer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteProfil.setIcon(icon5)
        self.pushButton_deleteProfil.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_deleteProfil.setFlat(True)
        self.pushButton_deleteProfil.setObjectName("pushButton_deleteProfil")
        self.tabWidget_options.addTab(self.tab_GestionProfil, "")
        self.tab_Langage = QtWidgets.QWidget()
        self.tab_Langage.setObjectName("tab_Langage")
        self.radioButton_language_French = QtWidgets.QRadioButton(self.tab_Langage)
        self.radioButton_language_French.setGeometry(QtCore.QRect(260, 40, 82, 17))
        self.radioButton_language_French.setObjectName("radioButton_language_French")
        self.radioButton_language_English = QtWidgets.QRadioButton(self.tab_Langage)
        self.radioButton_language_English.setGeometry(QtCore.QRect(260, 70, 82, 17))
        self.radioButton_language_English.setObjectName("radioButton_language_English")
        self.label_GFX_Arma3_2 = QtWidgets.QLabel(self.tab_Langage)
        self.label_GFX_Arma3_2.setGeometry(QtCore.QRect(220, 40, 31, 21))
        self.label_GFX_Arma3_2.setText("")
        self.label_GFX_Arma3_2.setPixmap(QtGui.QPixmap("gfx/france.png"))
        self.label_GFX_Arma3_2.setScaledContents(True)
        self.label_GFX_Arma3_2.setObjectName("label_GFX_Arma3_2")
        self.label_GFX_Arma3_3 = QtWidgets.QLabel(self.tab_Langage)
        self.label_GFX_Arma3_3.setGeometry(QtCore.QRect(220, 70, 31, 21))
        self.label_GFX_Arma3_3.setText("")
        self.label_GFX_Arma3_3.setPixmap(QtGui.QPixmap("gfx/royaumeunis.png"))
        self.label_GFX_Arma3_3.setScaledContents(True)
        self.label_GFX_Arma3_3.setObjectName("label_GFX_Arma3_3")
        self.label_GFX_Langage = QtWidgets.QLabel(self.tab_Langage)
        self.label_GFX_Langage.setGeometry(QtCore.QRect(30, 10, 101, 101))
        self.label_GFX_Langage.setText("")
        self.label_GFX_Langage.setPixmap(QtGui.QPixmap("gfx/globe.png"))
        self.label_GFX_Langage.setScaledContents(True)
        self.label_GFX_Langage.setObjectName("label_GFX_Langage")
        self.tabWidget_options.addTab(self.tab_Langage, "")
        self.tab_aPropos = QtWidgets.QWidget()
        self.tab_aPropos.setObjectName("tab_aPropos")
        self.label_GFX_aPropos = QtWidgets.QLabel(self.tab_aPropos)
        self.label_GFX_aPropos.setGeometry(QtCore.QRect(20, 5, 111, 106))
        self.label_GFX_aPropos.setText("")
        self.label_GFX_aPropos.setPixmap(QtGui.QPixmap("gfx/logo-gos.png"))
        self.label_GFX_aPropos.setScaledContents(True)
        self.label_GFX_aPropos.setObjectName("label_GFX_aPropos")
        self.tabWidget_options.addTab(self.tab_aPropos, "")
        self.groupBox_parametreExpert = QtWidgets.QGroupBox(self.tab_Options)
        self.groupBox_parametreExpert.setGeometry(QtCore.QRect(300, 10, 251, 301))
        self.groupBox_parametreExpert.setObjectName("groupBox_parametreExpert")
        self.label_GFX_parametresExperts = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_GFX_parametresExperts.setGeometry(QtCore.QRect(40, 20, 31, 31))
        self.label_GFX_parametresExperts.setText("")
        self.label_GFX_parametresExperts.setPixmap(QtGui.QPixmap("gfx/danger.png"))
        self.label_GFX_parametresExperts.setScaledContents(True)
        self.label_GFX_parametresExperts.setObjectName("label_GFX_parametresExperts")
        self.label_avertissementExpertParam = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_avertissementExpertParam.setGeometry(QtCore.QRect(90, 20, 131, 36))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_avertissementExpertParam.setFont(font)
        self.label_avertissementExpertParam.setObjectName("label_avertissementExpertParam")
        self.checkBox_procNumber = QtWidgets.QCheckBox(self.groupBox_parametreExpert)
        self.checkBox_procNumber.setEnabled(True)
        self.checkBox_procNumber.setGeometry(QtCore.QRect(10, 55, 191, 17))
        self.checkBox_procNumber.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_procNumber.setObjectName("checkBox_procNumber")
        self.lineEdit_procNumber = QtWidgets.QLineEdit(self.groupBox_parametreExpert)
        self.lineEdit_procNumber.setEnabled(False)
        self.lineEdit_procNumber.setGeometry(QtCore.QRect(50, 75, 31, 20))
        self.lineEdit_procNumber.setAcceptDrops(False)
        self.lineEdit_procNumber.setMaxLength(1)
        self.lineEdit_procNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_procNumber.setReadOnly(False)
        self.lineEdit_procNumber.setPlaceholderText("")
        self.lineEdit_procNumber.setObjectName("lineEdit_procNumber")
        self.horizontalSlider_procNumber = QtWidgets.QSlider(self.groupBox_parametreExpert)
        self.horizontalSlider_procNumber.setEnabled(False)
        self.horizontalSlider_procNumber.setGeometry(QtCore.QRect(100, 75, 131, 22))
        self.horizontalSlider_procNumber.setSizeIncrement(QtCore.QSize(0, 0))
        self.horizontalSlider_procNumber.setMinimum(1)
        self.horizontalSlider_procNumber.setMaximum(8)
        self.horizontalSlider_procNumber.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_procNumber.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_procNumber.setTickInterval(1)
        self.horizontalSlider_procNumber.setObjectName("horizontalSlider_procNumber")
        self.horizontalSlider_maxMemory = QtWidgets.QSlider(self.groupBox_parametreExpert)
        self.horizontalSlider_maxMemory.setEnabled(False)
        self.horizontalSlider_maxMemory.setGeometry(QtCore.QRect(100, 120, 131, 22))
        self.horizontalSlider_maxMemory.setSizeIncrement(QtCore.QSize(0, 0))
        self.horizontalSlider_maxMemory.setMinimum(256)
        self.horizontalSlider_maxMemory.setMaximum(8192)
        self.horizontalSlider_maxMemory.setSingleStep(2)
        self.horizontalSlider_maxMemory.setPageStep(64)
        self.horizontalSlider_maxMemory.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_maxMemory.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_maxMemory.setTickInterval(1)
        self.horizontalSlider_maxMemory.setObjectName("horizontalSlider_maxMemory")
        self.checkBox_maxMemory = QtWidgets.QCheckBox(self.groupBox_parametreExpert)
        self.checkBox_maxMemory.setEnabled(True)
        self.checkBox_maxMemory.setGeometry(QtCore.QRect(10, 100, 191, 17))
        self.checkBox_maxMemory.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_maxMemory.setObjectName("checkBox_maxMemory")
        self.lineEdit_maxMemory = QtWidgets.QLineEdit(self.groupBox_parametreExpert)
        self.lineEdit_maxMemory.setEnabled(False)
        self.lineEdit_maxMemory.setGeometry(QtCore.QRect(50, 120, 31, 20))
        self.lineEdit_maxMemory.setAcceptDrops(False)
        self.lineEdit_maxMemory.setMaxLength(4)
        self.lineEdit_maxMemory.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_maxMemory.setReadOnly(False)
        self.lineEdit_maxMemory.setPlaceholderText("")
        self.lineEdit_maxMemory.setObjectName("lineEdit_maxMemory")
        self.checkBox_maxVideoMemory = QtWidgets.QCheckBox(self.groupBox_parametreExpert)
        self.checkBox_maxVideoMemory.setEnabled(True)
        self.checkBox_maxVideoMemory.setGeometry(QtCore.QRect(10, 145, 191, 17))
        self.checkBox_maxVideoMemory.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_maxVideoMemory.setObjectName("checkBox_maxVideoMemory")
        self.lineEdit_maxVIDEOMemory = QtWidgets.QLineEdit(self.groupBox_parametreExpert)
        self.lineEdit_maxVIDEOMemory.setEnabled(False)
        self.lineEdit_maxVIDEOMemory.setGeometry(QtCore.QRect(50, 165, 31, 20))
        self.lineEdit_maxVIDEOMemory.setAcceptDrops(False)
        self.lineEdit_maxVIDEOMemory.setMaxLength(4)
        self.lineEdit_maxVIDEOMemory.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_maxVIDEOMemory.setReadOnly(False)
        self.lineEdit_maxVIDEOMemory.setPlaceholderText("")
        self.lineEdit_maxVIDEOMemory.setObjectName("lineEdit_maxVIDEOMemory")
        self.horizontalSlider_maxVIDEOMemory = QtWidgets.QSlider(self.groupBox_parametreExpert)
        self.horizontalSlider_maxVIDEOMemory.setEnabled(False)
        self.horizontalSlider_maxVIDEOMemory.setGeometry(QtCore.QRect(100, 165, 131, 22))
        self.horizontalSlider_maxVIDEOMemory.setSizeIncrement(QtCore.QSize(0, 0))
        self.horizontalSlider_maxVIDEOMemory.setMinimum(128)
        self.horizontalSlider_maxVIDEOMemory.setMaximum(4096)
        self.horizontalSlider_maxVIDEOMemory.setSingleStep(2)
        self.horizontalSlider_maxVIDEOMemory.setPageStep(32)
        self.horizontalSlider_maxVIDEOMemory.setProperty("value", 128)
        self.horizontalSlider_maxVIDEOMemory.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_maxVIDEOMemory.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_maxVIDEOMemory.setTickInterval(1)
        self.horizontalSlider_maxVIDEOMemory.setObjectName("horizontalSlider_maxVIDEOMemory")
        self.checkBox_extraThreads = QtWidgets.QCheckBox(self.groupBox_parametreExpert)
        self.checkBox_extraThreads.setEnabled(True)
        self.checkBox_extraThreads.setGeometry(QtCore.QRect(10, 190, 91, 17))
        self.checkBox_extraThreads.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_extraThreads.setObjectName("checkBox_extraThreads")
        self.comboBox_extraThreads = QtWidgets.QComboBox(self.groupBox_parametreExpert)
        self.comboBox_extraThreads.setEnabled(False)
        self.comboBox_extraThreads.setGeometry(QtCore.QRect(100, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_extraThreads.setFont(font)
        self.comboBox_extraThreads.setObjectName("comboBox_extraThreads")
        self.comboBox_extraThreads.addItem("")
        self.comboBox_extraThreads.addItem("")
        self.comboBox_extraThreads.addItem("")
        self.comboBox_extraThreads.addItem("")
        self.comboBox_extraThreads.addItem("")
        self.label_fileOperations = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_fileOperations.setEnabled(False)
        self.label_fileOperations.setGeometry(QtCore.QRect(70, 215, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_fileOperations.setFont(font)
        self.label_fileOperations.setObjectName("label_fileOperations")
        self.label_textureLoading = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_textureLoading.setEnabled(False)
        self.label_textureLoading.setGeometry(QtCore.QRect(70, 230, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_textureLoading.setFont(font)
        self.label_textureLoading.setObjectName("label_textureLoading")
        self.label_geometryLoading = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_geometryLoading.setEnabled(False)
        self.label_geometryLoading.setGeometry(QtCore.QRect(70, 245, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_geometryLoading.setFont(font)
        self.label_geometryLoading.setObjectName("label_geometryLoading")
        self.checkBox_hyperThreading = QtWidgets.QCheckBox(self.groupBox_parametreExpert)
        self.checkBox_hyperThreading.setGeometry(QtCore.QRect(10, 265, 191, 17))
        self.checkBox_hyperThreading.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.checkBox_hyperThreading.setObjectName("checkBox_hyperThreading")
        self.label_GFX_fileOperations = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_GFX_fileOperations.setEnabled(False)
        self.label_GFX_fileOperations.setGeometry(QtCore.QRect(50, 215, 12, 12))
        self.label_GFX_fileOperations.setText("")
        self.label_GFX_fileOperations.setPixmap(QtGui.QPixmap("gfx/valide.png"))
        self.label_GFX_fileOperations.setScaledContents(True)
        self.label_GFX_fileOperations.setObjectName("label_GFX_fileOperations")
        self.label_GFX_textureLoading = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_GFX_textureLoading.setEnabled(False)
        self.label_GFX_textureLoading.setGeometry(QtCore.QRect(50, 230, 12, 12))
        self.label_GFX_textureLoading.setText("")
        self.label_GFX_textureLoading.setPixmap(QtGui.QPixmap("gfx/valide.png"))
        self.label_GFX_textureLoading.setScaledContents(True)
        self.label_GFX_textureLoading.setObjectName("label_GFX_textureLoading")
        self.label_GFX_geometryLoading = QtWidgets.QLabel(self.groupBox_parametreExpert)
        self.label_GFX_geometryLoading.setEnabled(False)
        self.label_GFX_geometryLoading.setGeometry(QtCore.QRect(50, 245, 12, 12))
        self.label_GFX_geometryLoading.setText("")
        self.label_GFX_geometryLoading.setPixmap(QtGui.QPixmap("gfx/valide.png"))
        self.label_GFX_geometryLoading.setScaledContents(True)
        self.label_GFX_geometryLoading.setObjectName("label_GFX_geometryLoading")
        self.tabWidget_synchro.addTab(self.tab_Options, "")
        self.tab_synchro = QtWidgets.QWidget()
        self.tab_synchro.setObjectName("tab_synchro")
        self.label_synchro_title = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_title.setGeometry(QtCore.QRect(10, 10, 221, 46))
        font = QtGui.QFont()
        font.setFamily("Jokerman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_synchro_title.setFont(font)
        self.label_synchro_title.setScaledContents(False)
        self.label_synchro_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_title.setObjectName("label_synchro_title")
        self.label_synchro_subtitle = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_subtitle.setGeometry(QtCore.QRect(50, 50, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_subtitle.setFont(font)
        self.label_synchro_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_subtitle.setObjectName("label_synchro_subtitle")
        self.label_synchro_template = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_template.setGeometry(QtCore.QRect(10, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_template.setFont(font)
        self.label_synchro_template.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_template.setObjectName("label_synchro_template")
        self.label_synchro_template_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_template_state.setGeometry(QtCore.QRect(90, 100, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_template_state.setFont(font)
        self.label_synchro_template_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_template_state.setObjectName("label_synchro_template_state")
        self.label_synchro_template_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_template_debit.setGeometry(QtCore.QRect(380, 99, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_template_debit.setFont(font)
        self.label_synchro_template_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_template_debit.setObjectName("label_synchro_template_debit")
        self.pushButton_synchro_template_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_template_launch.setGeometry(QtCore.QRect(480, 99, 71, 21))
        self.pushButton_synchro_template_launch.setObjectName("pushButton_synchro_template_launch")
        self.progressBar_synchro_template_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_template_fichier.setGeometry(QtCore.QRect(170, 100, 206, 10))
        self.progressBar_synchro_template_fichier.setProperty("value", 0)
        self.progressBar_synchro_template_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_template_fichier.setTextVisible(False)
        self.progressBar_synchro_template_fichier.setObjectName("progressBar_synchro_template_fichier")
        self.progressBar_synchro_template_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_template_global.setGeometry(QtCore.QRect(170, 110, 206, 10))
        self.progressBar_synchro_template_global.setProperty("value", 0)
        self.progressBar_synchro_template_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_template_global.setTextVisible(False)
        self.progressBar_synchro_template_global.setObjectName("progressBar_synchro_template_global")
        self.textEdit_synchro_log = QtWidgets.QTextEdit(self.tab_synchro)
        self.textEdit_synchro_log.setEnabled(True)
        self.textEdit_synchro_log.setGeometry(QtCore.QRect(10, 340, 546, 126))
        self.textEdit_synchro_log.setAcceptDrops(False)
        self.textEdit_synchro_log.setToolTip("")
        self.textEdit_synchro_log.setReadOnly(True)
        self.textEdit_synchro_log.setAcceptRichText(True)
        self.textEdit_synchro_log.setObjectName("textEdit_synchro_log")
        self.label_synchro_islands = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_islands.setGeometry(QtCore.QRect(10, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_islands.setFont(font)
        self.label_synchro_islands.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_islands.setObjectName("label_synchro_islands")
        self.progressBar_synchro_islands_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_islands_fichier.setGeometry(QtCore.QRect(170, 130, 206, 11))
        self.progressBar_synchro_islands_fichier.setProperty("value", 0)
        self.progressBar_synchro_islands_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_islands_fichier.setTextVisible(False)
        self.progressBar_synchro_islands_fichier.setObjectName("progressBar_synchro_islands_fichier")
        self.label_synchro_islands_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_islands_debit.setGeometry(QtCore.QRect(380, 129, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_islands_debit.setFont(font)
        self.label_synchro_islands_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_islands_debit.setObjectName("label_synchro_islands_debit")
        self.label_synchro_islands_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_islands_state.setGeometry(QtCore.QRect(90, 130, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_islands_state.setFont(font)
        self.label_synchro_islands_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_islands_state.setObjectName("label_synchro_islands_state")
        self.progressBar_synchro_islands_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_islands_global.setGeometry(QtCore.QRect(170, 140, 206, 10))
        self.progressBar_synchro_islands_global.setProperty("value", 0)
        self.progressBar_synchro_islands_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_islands_global.setTextVisible(False)
        self.progressBar_synchro_islands_global.setObjectName("progressBar_synchro_islands_global")
        self.pushButton_synchro_islands_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_islands_launch.setGeometry(QtCore.QRect(480, 129, 71, 21))
        self.pushButton_synchro_islands_launch.setObjectName("pushButton_synchro_islands_launch")
        self.label_synchro_materiel_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_materiel_state.setGeometry(QtCore.QRect(90, 160, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_materiel_state.setFont(font)
        self.label_synchro_materiel_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_materiel_state.setObjectName("label_synchro_materiel_state")
        self.progressBar_synchro_materiel_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_materiel_fichier.setGeometry(QtCore.QRect(170, 160, 206, 10))
        self.progressBar_synchro_materiel_fichier.setProperty("value", 0)
        self.progressBar_synchro_materiel_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_materiel_fichier.setTextVisible(False)
        self.progressBar_synchro_materiel_fichier.setObjectName("progressBar_synchro_materiel_fichier")
        self.label_synchro_materiel = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_materiel.setGeometry(QtCore.QRect(10, 160, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_materiel.setFont(font)
        self.label_synchro_materiel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_materiel.setObjectName("label_synchro_materiel")
        self.label_synchro_materiel_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_materiel_debit.setGeometry(QtCore.QRect(380, 159, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_materiel_debit.setFont(font)
        self.label_synchro_materiel_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_materiel_debit.setObjectName("label_synchro_materiel_debit")
        self.progressBar_synchro_materiel_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_materiel_global.setGeometry(QtCore.QRect(170, 170, 206, 10))
        self.progressBar_synchro_materiel_global.setProperty("value", 0)
        self.progressBar_synchro_materiel_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_materiel_global.setTextVisible(False)
        self.progressBar_synchro_materiel_global.setObjectName("progressBar_synchro_materiel_global")
        self.pushButton_synchro_materiel_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_materiel_launch.setGeometry(QtCore.QRect(480, 159, 71, 21))
        self.pushButton_synchro_materiel_launch.setObjectName("pushButton_synchro_materiel_launch")
        self.label_synchro_framework_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_framework_debit.setGeometry(QtCore.QRect(380, 219, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_framework_debit.setFont(font)
        self.label_synchro_framework_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_framework_debit.setObjectName("label_synchro_framework_debit")
        self.pushButton_synchro_framework_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_framework_launch.setGeometry(QtCore.QRect(480, 219, 71, 21))
        self.pushButton_synchro_framework_launch.setObjectName("pushButton_synchro_framework_launch")
        self.label_synchro_framework = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_framework.setGeometry(QtCore.QRect(10, 219, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_framework.setFont(font)
        self.label_synchro_framework.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_synchro_framework.setObjectName("label_synchro_framework")
        self.progressBar_synchro_framework_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_framework_global.setGeometry(QtCore.QRect(170, 230, 206, 11))
        self.progressBar_synchro_framework_global.setProperty("value", 0)
        self.progressBar_synchro_framework_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_framework_global.setTextVisible(False)
        self.progressBar_synchro_framework_global.setObjectName("progressBar_synchro_framework_global")
        self.label_synchro_framework_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_framework_state.setGeometry(QtCore.QRect(90, 220, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_framework_state.setFont(font)
        self.label_synchro_framework_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_framework_state.setObjectName("label_synchro_framework_state")
        self.progressBar_synchro_framework_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_framework_fichier.setGeometry(QtCore.QRect(170, 220, 206, 11))
        self.progressBar_synchro_framework_fichier.setProperty("value", 0)
        self.progressBar_synchro_framework_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_framework_fichier.setTextVisible(False)
        self.progressBar_synchro_framework_fichier.setObjectName("progressBar_synchro_framework_fichier")
        self.label_synchro_units_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_units_state.setGeometry(QtCore.QRect(90, 190, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_units_state.setFont(font)
        self.label_synchro_units_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_units_state.setObjectName("label_synchro_units_state")
        self.label_synchro_units = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_units.setGeometry(QtCore.QRect(10, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_units.setFont(font)
        self.label_synchro_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_synchro_units.setObjectName("label_synchro_units")
        self.label_synchro_units_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_units_debit.setGeometry(QtCore.QRect(380, 189, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_units_debit.setFont(font)
        self.label_synchro_units_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_units_debit.setObjectName("label_synchro_units_debit")
        self.progressBar_synchro_units_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_units_global.setGeometry(QtCore.QRect(170, 200, 206, 11))
        self.progressBar_synchro_units_global.setProperty("value", 0)
        self.progressBar_synchro_units_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_units_global.setTextVisible(False)
        self.progressBar_synchro_units_global.setObjectName("progressBar_synchro_units_global")
        self.progressBar_synchro_units_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_units_fichier.setGeometry(QtCore.QRect(170, 190, 206, 10))
        self.progressBar_synchro_units_fichier.setProperty("value", 0)
        self.progressBar_synchro_units_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_units_fichier.setTextVisible(False)
        self.progressBar_synchro_units_fichier.setObjectName("progressBar_synchro_units_fichier")
        self.pushButton_synchro_units_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_units_launch.setGeometry(QtCore.QRect(480, 189, 71, 21))
        self.pushButton_synchro_units_launch.setObjectName("pushButton_synchro_units_launch")
        self.pushButton_synchro_client_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_client_launch.setGeometry(QtCore.QRect(480, 249, 71, 21))
        self.pushButton_synchro_client_launch.setObjectName("pushButton_synchro_client_launch")
        self.progressBar_synchro_client_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_client_fichier.setGeometry(QtCore.QRect(170, 250, 206, 11))
        self.progressBar_synchro_client_fichier.setProperty("value", 0)
        self.progressBar_synchro_client_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_client_fichier.setTextVisible(False)
        self.progressBar_synchro_client_fichier.setObjectName("progressBar_synchro_client_fichier")
        self.label_synchro_client = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_client.setGeometry(QtCore.QRect(10, 249, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_client.setFont(font)
        self.label_synchro_client.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_synchro_client.setObjectName("label_synchro_client")
        self.progressBar_synchro_client_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_client_global.setGeometry(QtCore.QRect(170, 260, 206, 11))
        self.progressBar_synchro_client_global.setProperty("value", 0)
        self.progressBar_synchro_client_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_client_global.setTextVisible(False)
        self.progressBar_synchro_client_global.setObjectName("progressBar_synchro_client_global")
        self.label_synchro_client_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_client_state.setGeometry(QtCore.QRect(90, 250, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_client_state.setFont(font)
        self.label_synchro_client_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_client_state.setObjectName("label_synchro_client_state")
        self.label_synchro_client_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_client_debit.setGeometry(QtCore.QRect(380, 249, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_client_debit.setFont(font)
        self.label_synchro_client_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_client_debit.setObjectName("label_synchro_client_debit")
        self.progressBar_synchro_test_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_test_global.setGeometry(QtCore.QRect(170, 290, 206, 11))
        self.progressBar_synchro_test_global.setProperty("value", 0)
        self.progressBar_synchro_test_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_test_global.setTextVisible(False)
        self.progressBar_synchro_test_global.setObjectName("progressBar_synchro_test_global")
        self.pushButton_synchro_test_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_test_launch.setGeometry(QtCore.QRect(480, 279, 71, 21))
        self.pushButton_synchro_test_launch.setObjectName("pushButton_synchro_test_launch")
        self.progressBar_synchro_test_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_test_fichier.setGeometry(QtCore.QRect(170, 280, 206, 11))
        self.progressBar_synchro_test_fichier.setProperty("value", 0)
        self.progressBar_synchro_test_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_test_fichier.setTextVisible(False)
        self.progressBar_synchro_test_fichier.setObjectName("progressBar_synchro_test_fichier")
        self.label_synchro_test = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_test.setGeometry(QtCore.QRect(10, 279, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_test.setFont(font)
        self.label_synchro_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_synchro_test.setObjectName("label_synchro_test")
        self.label_synchro_test_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_test_state.setGeometry(QtCore.QRect(90, 280, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_test_state.setFont(font)
        self.label_synchro_test_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_test_state.setObjectName("label_synchro_test_state")
        self.label_synchro_test_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_test_debit.setGeometry(QtCore.QRect(380, 279, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_test_debit.setFont(font)
        self.label_synchro_test_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_test_debit.setObjectName("label_synchro_test_debit")
        self.label_synchro_interclan_debit = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_interclan_debit.setGeometry(QtCore.QRect(380, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_interclan_debit.setFont(font)
        self.label_synchro_interclan_debit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_interclan_debit.setObjectName("label_synchro_interclan_debit")
        self.label_synchro_interclan_state = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_interclan_state.setGeometry(QtCore.QRect(90, 311, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_interclan_state.setFont(font)
        self.label_synchro_interclan_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_synchro_interclan_state.setObjectName("label_synchro_interclan_state")
        self.progressBar_synchro_interclan_fichier = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_interclan_fichier.setGeometry(QtCore.QRect(170, 310, 206, 11))
        self.progressBar_synchro_interclan_fichier.setProperty("value", 0)
        self.progressBar_synchro_interclan_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_interclan_fichier.setTextVisible(False)
        self.progressBar_synchro_interclan_fichier.setObjectName("progressBar_synchro_interclan_fichier")
        self.progressBar_synchro_interclan_global = QtWidgets.QProgressBar(self.tab_synchro)
        self.progressBar_synchro_interclan_global.setGeometry(QtCore.QRect(170, 320, 206, 10))
        self.progressBar_synchro_interclan_global.setProperty("value", 0)
        self.progressBar_synchro_interclan_global.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_synchro_interclan_global.setTextVisible(False)
        self.progressBar_synchro_interclan_global.setObjectName("progressBar_synchro_interclan_global")
        self.pushButton_synchro_interclan_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_interclan_launch.setGeometry(QtCore.QRect(480, 310, 71, 21))
        self.pushButton_synchro_interclan_launch.setObjectName("pushButton_synchro_interclan_launch")
        self.label_synchro_interclan = QtWidgets.QLabel(self.tab_synchro)
        self.label_synchro_interclan.setGeometry(QtCore.QRect(10, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_synchro_interclan.setFont(font)
        self.label_synchro_interclan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_synchro_interclan.setObjectName("label_synchro_interclan")
        self.pushButton_synchro_generale_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_generale_launch.setGeometry(QtCore.QRect(270, 20, 111, 41))
        self.pushButton_synchro_generale_launch.setObjectName("pushButton_synchro_generale_launch")
        self.pushButton_synchro_changelog_launch = QtWidgets.QPushButton(self.tab_synchro)
        self.pushButton_synchro_changelog_launch.setGeometry(QtCore.QRect(270, 60, 111, 21))
        self.pushButton_synchro_changelog_launch.setObjectName("pushButton_synchro_changelog_launch")
        self.checkBox_SynchroBeta = QtWidgets.QCheckBox(self.tab_synchro)
        self.checkBox_SynchroBeta.setGeometry(QtCore.QRect(420, 25, 70, 17))
        self.checkBox_SynchroBeta.setChecked(True)
        self.checkBox_SynchroBeta.setObjectName("checkBox_SynchroBeta")
        self.checkBox_SynchroInterclan = QtWidgets.QCheckBox(self.tab_synchro)
        self.checkBox_SynchroInterclan.setGeometry(QtCore.QRect(420, 55, 70, 17))
        self.checkBox_SynchroInterclan.setChecked(True)
        self.checkBox_SynchroInterclan.setObjectName("checkBox_SynchroInterclan")
        self.tabWidget_synchro.addTab(self.tab_synchro, "")
        self.pushButton_LaunchArma3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_LaunchArma3.setGeometry(QtCore.QRect(440, 590, 121, 51))
        self.pushButton_LaunchArma3.setObjectName("pushButton_LaunchArma3")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("GOS Launcher A3")
        self.label.setObjectName("label")
        self.comboBox_ChoixProfil = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_ChoixProfil.setGeometry(QtCore.QRect(20, 565, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ChoixProfil.setFont(font)
        self.comboBox_ChoixProfil.setObjectName("comboBox_ChoixProfil")
        self.toolButton_saveProfil = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_saveProfil.setGeometry(QtCore.QRect(170, 565, 41, 41))
        self.toolButton_saveProfil.setText("...")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("gfx/disquette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_saveProfil.setIcon(icon6)
        self.toolButton_saveProfil.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_saveProfil.setObjectName("toolButton_saveProfil")
        self.groupBox_info = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_info.setGeometry(QtCore.QRect(390, 0, 181, 71))
        self.groupBox_info.setMaximumSize(QtCore.QSize(16777215, 16777212))
        self.groupBox_info.setObjectName("groupBox_info")
        self.label_info_arma3 = QtWidgets.QLabel(self.groupBox_info)
        self.label_info_arma3.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label_info_arma3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_info_arma3.setObjectName("label_info_arma3")
        self.label_info_synchro = QtWidgets.QLabel(self.groupBox_info)
        self.label_info_synchro.setGeometry(QtCore.QRect(5, 50, 47, 16))
        self.label_info_synchro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_info_synchro.setObjectName("label_info_synchro")
        self.label_info_arma3_version = QtWidgets.QLabel(self.groupBox_info)
        self.label_info_arma3_version.setGeometry(QtCore.QRect(60, 30, 111, 16))
        self.label_info_arma3_version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_info_arma3_version.setObjectName("label_info_arma3_version")
        self.label_info_synchro_taille = QtWidgets.QLabel(self.groupBox_info)
        self.label_info_synchro_taille.setGeometry(QtCore.QRect(60, 50, 111, 16))
        self.label_info_synchro_taille.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_info_synchro_taille.setObjectName("label_info_synchro_taille")
        self.label_info_arma3.raise_()
        self.label_info_synchro.raise_()
        self.label_info_synchro_taille.raise_()
        self.label_info_arma3_version.raise_()
        self.checkBox_Arma3BattleEyes = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_Arma3BattleEyes.setGeometry(QtCore.QRect(25, 595, 131, 17))
        self.checkBox_Arma3BattleEyes.setChecked(False)
        self.checkBox_Arma3BattleEyes.setObjectName("checkBox_Arma3BattleEyes")
        self.checkBox_forceAdminMode = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_forceAdminMode.setGeometry(QtCore.QRect(25, 615, 131, 17))
        self.checkBox_forceAdminMode.setChecked(False)
        self.checkBox_forceAdminMode.setObjectName("checkBox_forceAdminMode")
        self.checkBox_reduceOnLaunch = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_reduceOnLaunch.setGeometry(QtCore.QRect(25, 635, 131, 17))
        self.checkBox_reduceOnLaunch.setChecked(False)
        self.checkBox_reduceOnLaunch.setObjectName("checkBox_reduceOnLaunch")
        self.label_Done = QtWidgets.QLabel(self.centralWidget)
        self.label_Done.setGeometry(QtCore.QRect(165, 605, 56, 16))
        self.label_Done.setText("")
        self.label_Done.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Done.setObjectName("label_Done")
        Fenetre_Principale.setCentralWidget(self.centralWidget)

        self.retranslateUi(Fenetre_Principale)
        self.tabWidget_synchro.setCurrentIndex(4)
        self.tabWidget_GOS.setCurrentIndex(0)
        self.tabWidget_MODs.setCurrentIndex(0)
        self.tabWidget_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Fenetre_Principale)

    def retranslateUi(self, Fenetre_Principale):
        _translate = QtCore.QCoreApplication.translate
        Fenetre_Principale.setWindowTitle(_translate("Fenetre_Principale", "GOS Launcher A3"))
        self.pushButton_Mods_Template_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Template_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Template_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Template), _translate("Fenetre_Principale", "TEMPLATE"))
        self.pushButton_Mods_Framework_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Framework_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Framework_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Framework), _translate("Fenetre_Principale", "FRAMEWORK"))
        self.pushButton_Mods_Islands_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Islands_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Islands_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Islands), _translate("Fenetre_Principale", "ISLANDS"))
        self.pushButton_Mods_Units_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Units_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Units_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Units), _translate("Fenetre_Principale", "UNITS"))
        self.pushButton_Mods_Materiel_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Materiel_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Materiel_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Materiel), _translate("Fenetre_Principale", "MATERIEL"))
        self.pushButton_Mods_Client_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Client_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Client_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Client), _translate("Fenetre_Principale", "CLIENT"))
        self.pushButton_Mods_Test_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Test_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Test_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab_Test), _translate("Fenetre_Principale", "TEST"))
        self.pushButton_Mods_Interclan_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_Interclan_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Interclan_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.tabWidget_GOS.setTabText(self.tabWidget_GOS.indexOf(self.tab), _translate("Fenetre_Principale", "INTERCLAN"))
        self.tabWidget_synchro.setTabText(self.tabWidget_synchro.indexOf(self.Tab_ModsGOS), _translate("Fenetre_Principale", "Mods GOS"))
        self.pushButton_Mods_A3_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_A3_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.pushButton_Mods_A3_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_Arma3), _translate("Fenetre_Principale", "ARMA3"))
        self.pushButton_Mods_Workshop_RefreshList.setText(_translate("Fenetre_Principale", "Rafraichir\n"
"liste"))
        self.pushButton_Mods_Workshop_InvSelect.setText(_translate("Fenetre_Principale", "Inverser\n"
"selection"))
        self.pushButton_Mods_Workshop_SelectAll.setText(_translate("Fenetre_Principale", "Selectionner\n"
"tous"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_Workshop), _translate("Fenetre_Principale", "WorkShop"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_DocsArma3), _translate("Fenetre_Principale", "Default Profile"))
        self.tabWidget_MODs.setTabText(self.tabWidget_MODs.indexOf(self.tab_OthersProfiles), _translate("Fenetre_Principale", "ARMA 3 Others Profile"))
        self.tabWidget_synchro.setTabText(self.tabWidget_synchro.indexOf(self.tab_MODs), _translate("Fenetre_Principale", "MODs"))
        self.pushButton_priorityTop.setText(_translate("Fenetre_Principale", "Haut"))
        self.pushButton_priorityPlus.setText(_translate("Fenetre_Principale", "+"))
        self.pushButton_priorityMinus.setText(_translate("Fenetre_Principale", "-"))
        self.pushButton_priorityBottom.setText(_translate("Fenetre_Principale", "Bas"))
        self.tabWidget_synchro.setTabText(self.tabWidget_synchro.indexOf(self.tab_priorityList), _translate("Fenetre_Principale", "Priorité"))
        self.groupBox_Parametre.setTitle(_translate("Fenetre_Principale", "Paramètres"))
        self.checkBox_nosplash.setText(_translate("Fenetre_Principale", "Passer écrans de démarrage"))
        self.checkBox_noPause.setText(_translate("Fenetre_Principale", "Pas de pause"))
        self.checkBox_emptyWorld.setText(_translate("Fenetre_Principale", "Monde vide au demarrage"))
        self.checkBox_showScriptError.setText(_translate("Fenetre_Principale", "Afficher les erreurs scripts"))
        self.checkBox_noCB.setText(_translate("Fenetre_Principale", "Arret gestion Multi-Core"))
        self.checkBox_AllowFileChange.setText(_translate("Fenetre_Principale", "Activer Modification du Fichier"))
        self.checkBox_noLogs.setText(_translate("Fenetre_Principale", "no logs"))
        self.checkBox_customCommand.setText(_translate("Fenetre_Principale", "custom"))
        self.lineEdit_customCommand.setPlaceholderText(_translate("Fenetre_Principale", "ligne de commande..."))
        self.checkBox_windowedMode.setText(_translate("Fenetre_Principale", "Mode fenêtré"))
        self.label_optionsXwindow.setText(_translate("Fenetre_Principale", "X="))
        self.label_optionsYwindow.setText(_translate("Fenetre_Principale", "Y="))
        self.checkBox_arma3_64bit.setText(_translate("Fenetre_Principale", "Arma 3 64 bit"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_outilGOS), _translate("Fenetre_Principale", "Outils GOS"))
        self.label_addAProfil.setText(_translate("Fenetre_Principale", "Ajouter un profil :"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_GestionProfil), _translate("Fenetre_Principale", "Profils"))
        self.radioButton_language_French.setText(_translate("Fenetre_Principale", "Français"))
        self.radioButton_language_English.setText(_translate("Fenetre_Principale", "Anglais"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_Langage), _translate("Fenetre_Principale", "Langage"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.tab_aPropos), _translate("Fenetre_Principale", "A propos"))
        self.groupBox_parametreExpert.setTitle(_translate("Fenetre_Principale", "Paramètres expert"))
        self.label_avertissementExpertParam.setText(_translate("Fenetre_Principale", "<html><head/><body><p align=\"center\">Modifier ces paramètres<br/>uniquement si vous savez<br/>ce que vous faites.</p></body></html>"))
        self.checkBox_procNumber.setText(_translate("Fenetre_Principale", "Nombre de processeurs"))
        self.checkBox_maxMemory.setText(_translate("Fenetre_Principale", "Memoire max (MB)"))
        self.checkBox_maxVideoMemory.setText(_translate("Fenetre_Principale", "Memoire VIDEO max (MB)"))
        self.checkBox_extraThreads.setText(_translate("Fenetre_Principale", "extra threads"))
        self.comboBox_extraThreads.setItemText(0, _translate("Fenetre_Principale", "0"))
        self.comboBox_extraThreads.setItemText(1, _translate("Fenetre_Principale", "1"))
        self.comboBox_extraThreads.setItemText(2, _translate("Fenetre_Principale", "3"))
        self.comboBox_extraThreads.setItemText(3, _translate("Fenetre_Principale", "5"))
        self.comboBox_extraThreads.setItemText(4, _translate("Fenetre_Principale", "7"))
        self.label_fileOperations.setText(_translate("Fenetre_Principale", "File operations"))
        self.label_textureLoading.setText(_translate("Fenetre_Principale", "Texture loading"))
        self.label_geometryLoading.setText(_translate("Fenetre_Principale", "Geometry loading"))
        self.checkBox_hyperThreading.setText(_translate("Fenetre_Principale", "autoriser hyperThreading"))
        self.tabWidget_synchro.setTabText(self.tabWidget_synchro.indexOf(self.tab_Options), _translate("Fenetre_Principale", "Options"))
        self.label_synchro_title.setText(_translate("Fenetre_Principale", "Synchro Zone"))
        self.label_synchro_subtitle.setText(_translate("Fenetre_Principale", "Rsync System"))
        self.label_synchro_template.setText(_translate("Fenetre_Principale", "@TEMPLATE :"))
        self.label_synchro_template_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.label_synchro_template_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.pushButton_synchro_template_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.textEdit_synchro_log.setDocumentTitle(_translate("Fenetre_Principale", "Log"))
        self.label_synchro_islands.setText(_translate("Fenetre_Principale", "@ISLANDS :"))
        self.label_synchro_islands_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.label_synchro_islands_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.pushButton_synchro_islands_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.label_synchro_materiel_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.label_synchro_materiel.setText(_translate("Fenetre_Principale", "@MATERIEL :"))
        self.label_synchro_materiel_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.pushButton_synchro_materiel_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.label_synchro_framework_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.pushButton_synchro_framework_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.label_synchro_framework.setText(_translate("Fenetre_Principale", "@FRAMEWORK :"))
        self.label_synchro_framework_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.label_synchro_units_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.label_synchro_units.setText(_translate("Fenetre_Principale", "@UNITS :"))
        self.label_synchro_units_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.pushButton_synchro_units_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.pushButton_synchro_client_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.label_synchro_client.setText(_translate("Fenetre_Principale", "@CLIENT :"))
        self.label_synchro_client_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.label_synchro_client_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.pushButton_synchro_test_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.label_synchro_test.setText(_translate("Fenetre_Principale", "@TEST :"))
        self.label_synchro_test_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.label_synchro_test_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.label_synchro_interclan_debit.setText(_translate("Fenetre_Principale", "0.00 Kb/s"))
        self.label_synchro_interclan_state.setText(_translate("Fenetre_Principale", "A jour"))
        self.pushButton_synchro_interclan_launch.setText(_translate("Fenetre_Principale", "Lancer"))
        self.label_synchro_interclan.setText(_translate("Fenetre_Principale", "@INTERCLAN :"))
        self.pushButton_synchro_generale_launch.setText(_translate("Fenetre_Principale", "Synchro\n"
"GENERALE"))
        self.pushButton_synchro_changelog_launch.setText(_translate("Fenetre_Principale", "Changelog"))
        self.checkBox_SynchroBeta.setText(_translate("Fenetre_Principale", "Beta"))
        self.checkBox_SynchroInterclan.setText(_translate("Fenetre_Principale", "Interclan"))
        self.tabWidget_synchro.setTabText(self.tabWidget_synchro.indexOf(self.tab_synchro), _translate("Fenetre_Principale", "Synchro"))
        self.pushButton_LaunchArma3.setText(_translate("Fenetre_Principale", "Lancer\n"
"Arma 3"))
        self.groupBox_info.setTitle(_translate("Fenetre_Principale", "Info"))
        self.label_info_arma3.setText(_translate("Fenetre_Principale", "Arma 3 :"))
        self.label_info_synchro.setText(_translate("Fenetre_Principale", "Synchro :"))
        self.label_info_arma3_version.setText(_translate("Fenetre_Principale", "v 1.64"))
        self.label_info_synchro_taille.setText(_translate("Fenetre_Principale", "A jour"))
        self.checkBox_Arma3BattleEyes.setText(_translate("Fenetre_Principale", "Arma3 BattleEyes"))
        self.checkBox_forceAdminMode.setText(_translate("Fenetre_Principale", "Force Mode Admin"))
        self.checkBox_reduceOnLaunch.setText(_translate("Fenetre_Principale", "Reduire au Lancement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fenetre_Principale = QtWidgets.QMainWindow()
    ui = Ui_Fenetre_Principale()
    ui.setupUi(Fenetre_Principale)
    Fenetre_Principale.show()
    sys.exit(app.exec_())

